---
- name: Create systemd override directory
  ansible.builtin.file:
    path: /etc/systemd/system/unbound.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: [unbound]

- name: Create override for unbound service
  ansible.builtin.copy:
    content: |
      [Unit]
            # restart forever
      StartLimitIntervalSec=0
      After=wg-quick@wg0.service
      Requires=sys-devices-virtual-net-wg0.device

      [Service]
            # restart forever
      Restart=always
      RestartSec=30
    dest: /etc/systemd/system/unbound.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  tags: [unbound]
