---
- name: "Check whether node needs initialization"
  ansible.builtin.find:
    paths: "{{ openbao_storage_dir }}"
    recurse: true
  register: "openbao_storage_files"
  notify: "Restart openbao"
  changed_when: openbao_storage_files.matched == 0
  tags: [openbao, openbao-configure, openbao-init]

- name: "Init openbao"
  when: openbao_storage_files.matched == 0 or openbao_force_init | bool
  tags: [openbao, openbao-configure, openbao-init]
  block:
    - name: "Add gpg keys"
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "{{ openbao_config_dir }}/gpg-key-{{ item.key }}"
        owner: "{{ openbao_user }}"
        group: "{{ openbao_group }}"
        mode: "0640"
      with_items: "{{ openbao_gpg_keys | dict2items }}"

    - name: "Run openbao operator init"
      ansible.builtin.command:
        cmd: "bao operator init -n=1 -t=1 -format=json {% if openbao_gpg_keys | length > 0 %}-pgp-keys={% for item in openbao_gpg_keys | dict2items %}{{ openbao_config_dir }}/gpg-key-{{ item.key }}{%- if not loop.last %},{% endif %}{% endfor %} -root-token-pgp-key={% for item in openbao_gpg_keys | dict2items %}{{ openbao_config_dir }}/gpg-key-{{ item.key }}{%- if not loop.last %},{% endif %}{% endfor %}{% endif %}"
        chdir: "{{ openbao_config_dir }}"
      environment:
        VAULT_ADDR: "{{ openbao_address }}"
        BAO_ADDR: "{{ openbao_address }}"
      run_once: true
      changed_when: false
      register: openbao_init

    - name: "Copy openbao init log"
      ansible.builtin.copy:
        content: "{{ openbao_init.stdout }}"
        dest: "{{ openbao_config_dir }}/openbao-init.json"
        mode: "0600"
      delegate_to: "{{ openbao_cluster_first_node }}"
      run_once: true

    - name: "Download openbao init log"
      ansible.builtin.copy:
        content: "{{ openbao_init.stdout }}"
        dest: "/tmp/openbao-init-{{ openbao_cluster_nodes_group }}-{{ openbao_cluster_name }}.json"
        mode: "0600"
      when: openbao_gpg_keys | length > 0
      delegate_to: localhost
      run_once: true
      become: false
