---
- name: "Run tasks hardening.yaml"
  ansible.builtin.include_tasks: "hardening.yaml"
  tags: [openbao, openbao-configure]

- name: "Run tasks install-package-manager.yaml"
  ansible.builtin.include_tasks: "install-package-manager.yaml"
  tags: [openbao, openbao-install]
  when: ansible_facts["os_family"] == "Debian" or ansible_facts["os_family"] == "RedHat"

- name: "Run tasks init.yaml"
  ansible.builtin.include_tasks: "init.yaml"
  tags: [openbao, openbao-configure, openbao-init]
