---
- name: Run block
  when: location is not defined
  tags: always

  block:
    - name: Detect if we are on an internal system
      ansible.builtin.set_fact:
        location: "{{ item.location }}"
      when: item.domain in ansible_host
      with_items: "{{ internal_domains }}"

    - name: Print debug information
      ansible.builtin.debug:
        msg: "Detected location: {{ location | default('') }}"
- name: Run block
  when: location is defined
  tags: [firewall, base]
  block:
    - name: Assemble list of fw_tags
      ansible.builtin.set_fact:
        fw_tags: "{{ local_hosts | dict2items | map(attribute='value') | flatten | selectattr('fw_tags', 'defined') | map(attribute='fw_tags') | flatten | unique | sort }}"

    - name: Print list of fw_tags
      ansible.builtin.debug:
        msg: "{{ fw_tags | to_nice_json }}"

    - name: Assemble local fw_tags
      ansible.builtin.set_fact:
        fw_tags_local_{{ item }}: "{{ local_hosts[location] | selectattr('fw_tags', 'defined') | selectattr('fw_tags', 'contains', item) | map(attribute='logical') | list }}"  # noqa: var-naming[no-jinja]
        fw_tags_global_{{ item }}: "{{ local_hosts | dict2items | rejectattr('key', 'equalto', location) | map(attribute='value') | flatten | selectattr('fw_tags', 'defined') | selectattr('fw_tags', 'contains', item) | map(attribute='logical') | list }}"  # noqa: var-naming[no-jinja]
      with_items: "{{ fw_tags }}"

    - name: Assemble combined fw_tags
      ansible.builtin.set_fact:
        fw_tags_{{ item }}: "{{ vars['fw_tags_local_' + item] + vars['fw_tags_global_' + item] }}"  # noqa: var-naming[no-jinja]
      with_items: "{{ fw_tags }}"
