---
- name: "Collect and transform firewall rules"
  when: datacenter | default('') | length > 0
  tags: [firewall, base]
  block:
    - name: Assemble list of fw_tags
      ansible.builtin.set_fact:
        fw_tags: "{{ local_hosts | dict2items | map(attribute='value') | flatten | selectattr('fw_tags', 'defined') | map(attribute='fw_tags') | flatten | unique | sort }}"  # noqa: var-naming[no-role-prefix]

    - name: Print list of fw_tags
      ansible.builtin.debug:
        msg: "{{ fw_tags | to_nice_json }}"

    - name: Assemble local fw_tags
      ansible.builtin.set_fact:
        fw_tags_local_{{ item }}: "{{ local_hosts[datacenter] | selectattr('fw_tags', 'defined') | selectattr('fw_tags', 'contains', item) | map(attribute='logical') | list }}"  # noqa: var-naming
        fw_tags_global_{{ item }}: "{{ local_hosts | dict2items | rejectattr('key', 'equalto', datacenter) | map(attribute='value') | flatten | selectattr('fw_tags', 'defined') | selectattr('fw_tags', 'contains', item) | map(attribute='logical') | list }}"  # noqa: var-naming
      with_items: "{{ fw_tags }}"

    - name: Assemble combined fw_tags
      ansible.builtin.set_fact:
        fw_tags_{{ item }}: "{{ vars['fw_tags_local_' + item] + vars['fw_tags_global_' + item] }}"  # noqa: var-naming
      with_items: "{{ fw_tags }}"
