---
- name: Enable fstrim timer
  ansible.builtin.systemd:
    name: fstrim.timer
    state: enabled
  failed_when: false
  tags: [base, fs]

- name: Add noatime option to appropriate filesystem entries in fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^([^#\s]+)\s+{{ item.mount | regex_escape }}\s+({{ item.fstype }})\s+([^\s]*?)(\s+\d+\s+\d+)(.*)$'
    line: '\1 {{ item.mount }} \2 \3,noatime\4\5'
    backrefs: yes
  when: item.fstype in ['ext2', 'ext3', 'ext4', 'xfs', 'btrfs'] and 'noatime' not in (item.options | default(''))
  with_items: "{{ ansible_mounts | selectattr('fstype', 'match', '^(ext[234]|xfs|btrfs)$') | list }}"
  notify: remount filesystems
  tags: [base, fs]
