---
- name: Enable fstrim timer
  ansible.builtin.systemd:
    name: fstrim.timer
    state: enabled
  failed_when: false
  tags: [base, fs]

- name: Make sure mountpoints use 'noatime'
  ansible.posix.mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }},noatime"
    state: present
  with_items: "{{ ansible_mounts }}"
  when:
    # disable for now
    - false
    - base_mount_set_noatime
    - item.options.find(",") >= 0
    - item.options.find("noatime") == -1
    - item.fstype not in ["vfat", "fuse.gocryptfs", "fuse"]
  #    -item.fstype.find("vfat") == -1
  #    - item.fstype.find("gocryptfs") == -1
  #    - item.fstype.find("fuse") == -1
  tags: [base, mounts]
