---
- name: Add private CA
  ansible.builtin.copy:
    content: "{{ pki_soerenschneider_ca_crt }}"
    dest: "{{ pki_soerenschneider_ca_file }}"
    owner: root
    group: "{% if ansible_system == 'Linux' %}root{% else %}wheel{% endif %}"
    mode: "0644"
  tags: [base, pki]

- name: Run block
  tags: [pki]
  block:
    - name: Add script to update ca cert
      ansible.builtin.template:
        src: fetch-pki-ca.sh.j2
        dest: /usr/local/sbin/fetch-pki-ca.sh
        owner: root
        group: root
        mode: "0750"

    - name: Schedule fetching cert
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: /etc/systemd/system/{{ item }}
        owner: root
        group: root
        mode: "0644"
      with_items: [fetch-pki-ca.service, fetch-pki-ca.timer]

    - name: Start and enable service
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items: [fetch-pki-ca.service, fetch-pki-ca.timer]
