---
- name: Add private CA
  ansible.builtin.copy:
    content: "{{ pki_soerenschneider_ca_crt }}"
    dest: "{{ pki_soerenschneider_ca_file }}"
    owner: root
    group: "{% if ansible_system == 'Linux' %}root{% else %}wheel{% endif %}"
    mode: "0644"
  tags: [base, pki]
