---
- name: Run block
  ansible.builtin.set_fact:
    local_binary: ""
    installed_version: ""
    desired_version: "{{ dufs_version | default('') }}"
    download_archive: ""
    download_signature: ""
    stopped_service: ""
    github_release: ""
    go_os: ""
    go_arch: ""
    checksum_signature_file: ""
    checksum_file: ""
    full_filename: ""
    release_checksum: ""
  tags: [dufs, dufs-install, deps]

- name: Check for existing binary
  ansible.builtin.stat:
    path: /usr/local/bin/{{ binary_name }}
  register: local_binary
  tags: [dufs, dufs-install, deps]

- name: Check installed version
  when: local_binary.stat.exists
  tags: [dufs, dufs-install, deps]
  block:
    - name: Check installed version
      ansible.builtin.shell:
        cmd: "set -o pipefail &&  /usr/local/bin/{{ binary_name }} --version 2>&1 | awk '{print $2}'"
        executable: /bin/bash
      register: installed_version
      changed_when: false

    - name: Register local version
      ansible.builtin.set_fact:
        installed_version: "v{{ installed_version.stdout }}"
      changed_when: false

    - name: Print debug information
      ansible.builtin.debug:
        msg: "Installed version: {{ installed_version }}"
      changed_when: false

- name: Fetch latest release information from github
  when: desired_version is not defined or not desired_version
  tags: [dufs, dufs-install, deps]
  block:
    - name: Print debug information
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ github_repo }}/releases/latest
        return_content: true
      register: github_release
      retries: 3
      delay: 5
      until: github_release is not failed

    - name: Set github release
      ansible.builtin.set_fact:
        desired_version: "{{ github_release.json.tag_name }}"
      changed_when: false

    - name: Print latest GitHub version
      ansible.builtin.debug:
        msg: "Latest GitHub version: {{ desired_version }}"
      changed_when: false

- name: Run block
  when: not local_binary.stat.exists or desired_version != installed_version
  tags: [dufs, dufs-install, deps]
  block:
    - name: Generate temp dir
      become: false
      ansible.builtin.tempfile:
        state: directory
        suffix: "{{ binary_name }}"
      register: _download_dir

    - name: Set vars for generating download link
      ansible.builtin.set_fact:
        go_os: "{% if ansible_system | lower == 'linux' %}unknown-linux-musl{% else %}ansible_system | lower{% endif %}"
        go_arch: "{{ 'x86_64' if ansible_architecture == 'x86_64' else 'arm' if ansible_architecture == 'armv6l' else 'armv7' if ansible_architecture == 'armv7l' else 'aarch64' if ansible_architecture == 'aarch64' }}"
      changed_when: false

    - name: Set filenames
      ansible.builtin.set_fact:
        full_filename: "{{ binary_name }}-{{ desired_version }}-{{ go_arch }}-{{ go_os }}.tar.gz"
        _download_dir: "{{ _download_dir.path }}"
      changed_when: false

    - name: Download archive
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/{{ github_repo }}/releases/download/{{ desired_version }}/{{ full_filename }}"
        dest: "{{ _download_dir }}/{{ full_filename }}"
        mode: "0640"
      register: download_archive
      until: download_archive is succeeded
      retries: 1
      delay: 2

    - name: Unpack binaries from archive
      become: false
      ansible.builtin.unarchive:
        src: "{{ _download_dir }}/{{ full_filename }}"
        dest: "{{ _download_dir }}"
        remote_src: true
      check_mode: false

    - name: Stop service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: stopped
      failed_when: false
      register: stopped_service

    - name: Copy binaries
      ansible.builtin.copy:
        src: "{{ _download_dir }}/dufs"
        dest: /usr/local/bin/dufs
        remote_src: true
        mode: "0755"
        owner: root
        group: root
      notify: [Restart dufs]

  always:
    - name: Delete downloaded files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items: ["{{ _download_dir }}"]
      failed_when: false

    - name: Restart service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: restarted
      when: stopped_service is defined and stopped_service is changed
