---
- name: Install needrestart (RHEL)
  when: [ansible_os_family | lower == "redhat", ansible_distribution | lower != "fedora"]
  tags: [automatic-sysupdates, needrestart]
  block:
    - name: Enable crb/powertools repo for redhat
      ansible.builtin.command: dnf config-manager --set-enabled crb
      changed_when: true

    - name: "Run tasks install-github.yml"
      ansible.builtin.include_tasks: install-github.yaml

- name: Install needrestart (Debian)
  when: ansible_os_family | lower == "debian"
  ansible.builtin.package:
    name: needrestart
  tags: [automatic-sysupdates, needrestart]

- name: Set costum needrestart config
  ansible.builtin.template:
    src: needrestart.conf.j2
    dest: /etc/needrestart/conf.d/needrestart.conf
    owner: root
    group: root
    mode: "0644"
  tags: [automatic-sysupdates, needrestart]

- name: Force autorestart of some services
  ansible.builtin.lineinfile:
    path: /etc/needrestart/needrestart.conf
    regex: qr\(\^{{ item }}\)
    line: "#    qr(^{{ item }}) => 0,"
  with_items: "{{ needrestart_force_restart_services }}"
  tags: [automatic-sysupdates, needrestart]
