---
# renovate: datasource=github-tags depName=mariadb
mariadb_cluster_version: "11.8.2"
mariadb_cluster_image: "mariadb:{{ mariadb_cluster_version }}"

# renovate: datasource=github-tags depName=prom/mysqld-exporter
mariadb_cluster_mysqld_exporter_version: "v0.17.2"
mariadb_cluster_mysqld_exporter_image: "prom/mysqld-exporter:{{ mariadb_cluster_mysqld_exporter_version }}"

mariadb_cluster_user: "mariadb"
mariadb_cluster_group: "mariadb"

mariadb_cluster_replication_user: "replication"
mariadb_cluster_base_dir: "/var/lib/mariadb"
mariadb_cluster_storage_dir: "{{ mariadb_cluster_base_dir }}/data"
mariadb_cluster_certs_dir: "{{ mariadb_cluster_base_dir }}/certs"
mariadb_cluster_initdb_dir: "{{ mariadb_cluster_base_dir }}/initdb"
mariadb_cluster_galera_cluster_name: prd

mariadb_cluster_container_name: "mariadb"
mariadb_cluster_docker_network: "mariadb-cluster"
mariadb_cluster_certificate_paths:
  - "{{ mariadb_cluster_certs_dir }}/ca.crt"
  - "{{ mariadb_cluster_certs_dir }}/sst-ca.crt"
  - "{{ mariadb_cluster_certs_dir }}/sst.crt"
  - "{{ mariadb_cluster_certs_dir }}/tls.crt"
  - "{{ mariadb_cluster_certs_dir }}/wsrep.crt"
  - "{{ mariadb_cluster_certs_dir }}/wsrep-ca.crt"

mariadb_cluster_online_hosts: []
mariadb_cluster_ansible_group: "dbs"
mariadb_cluster_preferred_donors: []

mariadb_cluster_master: "{{ groups[mariadb_cluster_ansible_group][1] }}"

mariadb_cluster_galera_backup_user: backup

mariadb_cluster_galera_cluster_address_default: "gcomm://{% for node in groups[mariadb_cluster_ansible_group] %}{{ node }}:4567{% if not loop.last %},{% endif %}{% endfor %}"
mariadb_cluster_galera_cluster_address: "{{ mariadb_cluster_galera_cluster_address_default }}"
