---
collections:
  - name: community.general
    version: 11.4.3
  - name: community.docker
    version: 4.8.6
  - name: community.sops
    version: 2.2.7
  - name: "community.crypto"
    version: 3.1.0
  - name: ansible.posix
    version: 2.1.0
