---
collections:
  - name: community.general
    version: 11.4.0
  - name: community.docker
    version: 4.8.1
  - name: community.sops
    version: 2.2.4
  - name: "community.crypto"
    version: 3.0.4
  - name: ansible.posix
    version: 2.1.0
