---
collections:
  - name: community.general
    version: 11.4.1
  - name: community.docker
    version: 4.8.3
  - name: community.sops
    version: 2.2.7
  - name: "community.crypto"
    version: 3.0.5
  - name: ansible.posix
    version: 2.1.0
