---
collections:
  - name: community.general
    version: 13.2.0
  - name: community.docker
    version: 5.2.1
  - name: community.sops
    version: 2.4.0
  - name: "community.crypto"
    version: 3.3.0
  - name: ansible.posix
    version: 2.2.2
