---
- name: Disable autoreboot
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items: [autoreboot.service, autoreboot.timer, autoreboot-onboot.timer]
  failed_when: false
  tags: [conditional_reboot, conditional_reboot-configure]

- name: Remove systemd units
  ansible.builtin.file:
    path: /etc/systemd/system/{{ item }}
    state: absent
  with_items: [conditional-reboot.service, conditional-reboot.timer, autoreboot-boot.timer]
  tags: [conditional_reboot, conditional_reboot-configure]
