---
- name: Create samba users on system
  ansible.builtin.user:
    name: "{{ item.name }}"
    create_home: false
    shell: /bin/false
    password: "!"
  when: item.create_user
  with_items: "{{ samba_create_users }}"
  no_log: true
  tags: [samba, samba-configure, samba-users]

- name: Create samba user logins
  ansible.builtin.shell: set -o pipefail && (echo "{{ item.pass }}"; echo "{{ item.pass }}") | sudo smbpasswd -a -s {{ item.name }}
  with_items: "{{ samba_create_users | default([]) }}"
  no_log: true
  changed_when: true
  tags: [samba, samba-configure, samba-users]
