
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  #config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "apollo.yml"
    ansible.vault_password_file = "~/.ansible/pw"
    ansible.groups = {
      "apollo" => ["default"]
    }
  end
end

