---
ssh_users_group: ssh
ssh_users: []
ssh_2fa_users: []
ssh_2fa_enabled: false
ssh_force_pubkey_and_2fa: false
ssh_2fa_user_group: ssh2fa
ssh_otp_only: {}
ssh_otp_only_group: ssh_otp_only

ssh_user_ca_key_file: /etc/ssh/ca_user_key.pub

ssh_update_listener_wg_down_ips:
  - "0.0.0.0"
  - "::"
# ssh_update_listener_wg_up_ips: []
ssh_update_listener_on_calendar: "*:0/15"
