---
- name: Install prometheus usage exporter
  ansible.builtin.template:
    src: rclone_usage.j2
    dest: /usr/local/bin/rclone_usage
    owner: root
    group: root
    mode: "0755"
  tags: [rclone, rclone-exporter]

- name: Add cronjob to generate usage statistics
  ansible.builtin.cron:
    name: rclone-exporter-{{ rclone_usage_cron.drives | join(",") }}
    hour: "{{ rclone_usage_cron.hour | default(12) }}"
    minute: "{{ rclone_usage_cron.minute | default(0) }}"
    weekday: '{{ rclone_usage_cron.weekday | default("*") }}'
    user: "{{ rclone_usage_cron.user }}"
    job: /usr/local/bin/rclone_usage {{ rclone_usage_cron.drives | join(" ") }}
  when: rclone_usage_cron is defined
  tags: [rclone, rclone-exporter]
