---
- name: "Run tasks install.yml"
  ansible.builtin.include_tasks: install.yml
  tags: [rclone, rclone-configure]

- name: "Run tasks configure.yml"
  ansible.builtin.include_tasks: configure.yml
  tags: [rclone, rclone-configure]

- name: "Run tasks exporter.yml"
  ansible.builtin.include_tasks: exporter.yml
  tags: [rclone, rclone-exporter]

- name: "Run tasks backups.yml"
  ansible.builtin.include_tasks: backups.yml
  tags: [rclone, rclone-backups]
