---
# renovate: datasource=github-releases depName=openbao/openbao
openbao_version: v2.6.1

# renovate: datasource=github-releases depName=openbao/openbao-plugins
openbao_plugin_secret_aws_version: "secrets-aws-v0.2.0"

openbao_user: "openbao"
openbao_group: "openbao"

openbao_address: "http://localhost:{{ openbao_port }}"
openbao_listen_address: "0.0.0.0:{{ openbao_port }}"
openbao_port: 8200

openbao_dir: "/etc/openbao.d"
openbao_plugin_dir: "/opt/openbao/plugins"
openbao_storage_dir: "{{ openbao_dir }}/storage"
openbao_config_file: "{{ openbar_dir }}/openbao.hcl"
openbao_ui: true

openbao_gpg_key_path: "/usr/share/keyrings/openbao-archive-keyring.gpg"
openbao_apt_repo_uri: "https://pkgs.openbao.org/deb/"
openbao_apt_repo_file: "/etc/apt/sources.list.d/openbao.sources"
openbao_rpm_baseurl: "https://pkgs.openbao.org/rpm/$basearch"
openbao_rpm_repo_file: "/etc/yum.repos.d/openbao.repo"
openbao_rpm_gpg_key_path: "/etc/pki/rpm-gpg/openbao-gpg-pub.asc"

# openbao_gpg_keys is used to encrypt root token when initializing openbao
openbao_gpg_keys: {}
openbao_allow_insecure: false
openbao_tls_key: ""
openbao_tls_crt: ""
openbao_ansible_group_name: vault
openbao_configure_server: true

openbao_audit_log: "/var/log/openbao-audit.log"

openbao_cluster_name: "prod"
openbao_cluster_nodes_group: "vault"
openbao_cluster_first_node: "{{ groups[openbao_cluster_nodes_group][0] }}"
openbao_gpg_fingerprint: "66D15FDD87287219C8E15478D200CD702853E6D0"
