---
- name: Delete old stuff
  ansible.builtin.systemd:
    enabled: false
    name: "{{ item }}"
    state: stopped
  failed_when: false
  tags: [tunnelguard, tunnelguard-configure]
  with_items: [ssh-key-signer.service, ssh-key-signer.timer]

- name: Run block
  ansible.builtin.include_tasks: install-github.yml
  vars:
    binary_name: tunnelguard
    github_repo: soerenschneider/tunnelguard
    service_name: tunnelguard
  tags: [tunnelguard, tunnelguard-configure]

- name: Create systemd unit
  ansible.builtin.template:
    src: tunnelguard.service.j2
    dest: "/etc/systemd/system/tunnelguard.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart tunnelguard"
  tags: [tunnelguard, tunnelguard-configure]

- name: "Run block"
  when: tunnelguard_config is defined
  tags: [tunnelguard, tunnelguard-configure]
  block:
    - name: "Create config"
      ansible.builtin.copy:
        content: "{{ tunnelguard_config | to_nice_json(indent=2) }}"
        dest: "{{ tunnelguard_config_file }}"
        owner: "root"
        group: "root"
        mode: "0600"
      notify: "Restart tunnelguard"

    - name: "Enable and start units"
      ansible.builtin.systemd:
        name: "tunnelguard.service"
        daemon_reload: true
        enabled: true
        state: "started"
