---
- name: Install cockroachdb cluster
  hosts: dbs
  become: true
  gather_facts: true
  tasks:
    - name: Create cockroachdb user
      ansible.builtin.user:
        name: "{{ cockroachdb_user }}"
        system: true
      tags: [cockroachdb]

    - name: Create cockroachdb dir
      ansible.builtin.file:
        path: /var/lib/cockroachdb
        state: directory
        owner: "{{ cockroachdb_user }}"
        group: root
        mode: "0750"
      tags: [cockroachdb]

    - name: Create cockroachdb dir storage
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ cockroachdb_user }}"
        group: root
        mode: "0700"
      with_items: [/var/lib/cockroachdb/storage, /var/lib/cockroachdb/certs]
      tags: [docker, cockroachdb]
- name: Upsert
  ansible.builtin.import_playbook: cockroachdb-cluster-upsert.yml
