---
- name: Install unattended-upgrades and needrestart
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    install_recommends: false
    update_cache: true
  tags: [automatic-sysupdates]

- name: Create APT auto-upgrades configuration
  ansible.builtin.template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
  tags: [automatic-sysupdates]

- name: Create unattended-upgrades configuration
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
  tags: [automatic-sysupdates]

- name: Create override directory for update timer
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: directory
    oautoreboot_hourwner: root
    group: root
    mode: "0750"
  when: automatic_sysupdates_unattended_daily_time | length > 0
  tags: [automatic-sysupdates]

- name: Create override for upgrade timer
  ansible.builtin.template:
    src: upgrade-override.conf.j2
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
    owner: root
    group: root
    mode: "0640"
  when: automatic_sysupdates_unattended_daily_time | length > 0
  notify: Reload systemd
  tags: [automatic-sysupdates]

- name: Create override directory for upgrade timer
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory
    owner: root
    group: root
    mode: "0750"
  when: automatic_sysupdates_unattended_daily_upgrade_time | length > 0
  tags: [automatic-sysupdates]

- name: Create override for upgrade timer
  ansible.builtin.template:
    src: upgrade-override.conf.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    owner: root
    group: root
    mode: "0640"
  when: automatic_sysupdates_unattended_daily_upgrade_time | length > 0
  notify: Reload systemd
  tags: [automatic-sysupdates]
