---
- name: "Run tasks dnf.yml"
  ansible.builtin.include_tasks: dnf.yml
  when: ansible_os_family == 'RedHat'
  tags: always

- name: "Run tasks apt.yml"
  ansible.builtin.include_tasks: apt.yml
  when: ansible_os_family == 'Debian'
  tags: always

- name: "Run role needrestart"
  ansible.builtin.include_role:
    name: needrestart
  tags: always
