---
- name: Run block
  when: ['ansible_distribution not in [ "Debian", "Ubuntu", "Fedora" ]']
  tags: [automatic-sysupdates, needrestart]
  block:
    - name: Install requirements CentOS
      ansible.builtin.dnf:
        name: [perl-ExtUtils-MakeMaker, perl-Module-Find, perl-Proc-ProcessTable, perl-Sort-Naturally, perl-libintl-perl]
      when: ansible_distribution == "CentOS"

    - name: Check for latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/liske/needrestart/releases/latest
        return_content: true
      when: needrestart_version is not defined or not needrestart_version
      register: needrestart_latest

    - name: Extract version information from json
      ansible.builtin.set_fact:
        needrestart_version: "{{ needrestart_latest.json.tag_name }}"
      when: needrestart_version is not defined or not needrestart_version

    - name: "Clone respository version: {{ needrestart_version }}"
      ansible.builtin.git:
        repo: https://github.com/liske/needrestart.git
        dest: /opt/needrestart
        version: "{{ needrestart_version }}"
      register: needrestart_clone

    - name: Install needrestart
      ansible.builtin.command: make install
      when: needrestart_clone is changed  # noqa: no-handler
      args:
        chdir: /opt/needrestart
      changed_when: true

- name: Install needrestart
  ansible.builtin.package:
    name: needrestart
  when: ansible_distribution in [ "Debian", "Ubuntu", "Fedora" ]
  tags: [automatic-sysupdates, needrestart]

- name: Set costum needrestart config
  ansible.builtin.template:
    src: needrestart.conf.j2
    dest: /etc/needrestart/conf.d/needrestart.conf
    owner: root
    group: root
    mode: "0644"
  tags: [automatic-sysupdates, needrestart]

- name: Force autorestart of some services
  ansible.builtin.lineinfile:
    path: /etc/needrestart/needrestart.conf
    regex: qr\(\^{{ item }}\)
    line: "#    qr(^{{ item }}) => 0,"
  with_items: "{{ needrestart_force_restart_services }}"
  tags: [automatic-sysupdates, needrestart]

- name: Run block
  when: ansible_os_family == "RedHat"
  tags: [automatic-sysupdates, needrestart]
  block:
    - name: Detect python3 sitepath
      ansible.builtin.command: python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])'
      register: python3_sitepath_output
      changed_when: false

    - name: Set plugin path
      ansible.builtin.set_fact:
        sitepath: "{{ python3_sitepath_output.stdout }}"

    - name: Install DNF plugin
      ansible.builtin.template:
        src: needrestart.py.j2
        dest: "{{ sitepath }}/dnf-plugins/needrestart.py"
        owner: root
        group: root
        mode: "0640"
