---
- name: "Set variables"
  ansible.builtin.set_fact:
    device_stalker_local_binary: ""
    device_stalker_installed_version: ""
    device_stalker_desired_version: "{{ device_stalker_version | default('') }}"
    device_stalker_download_archive: ""
    device_stalker_download_signature: ""
    device_stalker_stopped_service: ""
    device_stalker_github_release: ""
    device_stalker_go_os: ""
    device_stalker_go_arch: ""
    device_stalker_checksum_signature_file: ""
    device_stalker_checksum_file: ""
    device_stalker_full_filename: ""
    device_stalker_release_checksum: ""
  tags: [device-stalker, device-stalker-install, deps]

- name: Check for existing binary
  ansible.builtin.stat:
    path: "/usr/local/bin/{{ binary_name }}"
  register: device_stalker_local_binary
  tags: [device-stalker, device-stalker-install, deps]

- name: Check installed version
  when: device_stalker_local_binary.stat.exists
  tags: [device-stalker, device-stalker-install, deps]
  block:
    - name: Check installed version
      ansible.builtin.shell:
        cmd: "set -o pipefail && /usr/local/bin/{{ binary_name }} -version 2>&1 | awk '{print $2}'"
        executable: /bin/bash
      register: device_stalker_installed_version
      changed_when: false

    - name: Register local version
      ansible.builtin.set_fact:
        device_stalker_installed_version: "{{ device_stalker_installed_version.stdout }}"
      changed_when: false

    - name: Print installed version
      ansible.builtin.debug:
        msg: "Installed version: {{ device_stalker_installed_version }}"
      changed_when: false

- name: Fetch latest release information from github
  when: device_stalker_desired_version is not defined or not device_stalker_desired_version
  tags: [device-stalker, device-stalker-install, deps]
  block:
    - name: Check the latest version
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ github_repo }}/releases/latest"
        return_content: true
      register: device_stalker_github_release
      retries: 3
      delay: 5
      until: device_stalker_github_release is not failed

    - name: Set github release
      ansible.builtin.set_fact:
        device_stalker_desired_version: "{{ device_stalker_github_release.json.tag_name }}"
      changed_when: false

    - name: Print latest GitHub version
      ansible.builtin.debug:
        msg: "Latest GitHub version: {{ device_stalker_desired_version }}"
      changed_when: false

- name: Install binary
  when: not device_stalker_local_binary.stat.exists or device_stalker_desired_version != device_stalker_installed_version
  tags: [device-stalker, device-stalker-install, deps]
  block:
    - name: Generate temp dir
      become: false
      ansible.builtin.tempfile:
        state: "directory"
        suffix: "{{ binary_name }}"
      register: device_stalker_download_dir

    - name: Set vars for generating download link
      ansible.builtin.set_fact:
        device_stalker_go_os: "{{ ansible_system | lower }}"
        device_stalker_go_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'armv6' if ansible_architecture == 'armv6l' else 'armv7' if ansible_architecture == 'armv7l' else 'aarch64' if ansible_architecture == 'aarch64' }}"
        device_stalker_download_dir: "{{ device_stalker_download_dir.path }}"
        device_stalker_extraction_dir: "{{ device_stalker_download_dir.path }}/{{ binary_name }}"
      changed_when: false

    - name: Set filenames
      ansible.builtin.set_fact:
        device_stalker_checksum_signature_file: "{{ device_stalker_download_dir }}/{{ binary_name }}-checksums.sha256.sig"
        device_stalker_checksum_file: "{{ device_stalker_download_dir }}/{{ binary_name }}-checksums.sha256"
        device_stalker_full_filename: "{{ binary_name }}-{{ device_stalker_go_os }}-{{ device_stalker_go_arch }}"
      changed_when: false

    - name: Get checksum for archive
      ansible.builtin.set_fact:
        device_stalker_release_checksum: "{{ item.split(' ')[0] }}"
      when:
        - device_stalker_full_filename in item
        - (not device_stalker_local_binary.stat.exists or device_stalker_installed_version != device_stalker_desired_version)
      with_items:
        - "{{ lookup('url', 'https://github.com/{{ github_repo }}/releases/download/' + device_stalker_desired_version + '/checksum.sha256', wantlist=True) | list }}"

    - name: Download binary
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/{{ github_repo }}/releases/download/{{ device_stalker_desired_version }}/{{ device_stalker_full_filename }}"
        dest: "{{ device_stalker_download_dir }}/{{ device_stalker_full_filename }}"
        checksum: "sha256:{{ device_stalker_release_checksum }}"
        mode: "0640"
      register: device_stalker_download_archive
      until: device_stalker_download_archive is succeeded
      retries: 5
      delay: 2

    - name: Download release checksum
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/{{ github_repo }}/releases/download/{{ device_stalker_desired_version }}/checksum.sha256"
        dest: "{{ device_stalker_checksum_file }}"
        mode: "0640"
      register: device_stalker_download_signature
      until: device_stalker_download_signature is succeeded
      retries: 5
      delay: 2

    - name: Download release checksum signature
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/{{ github_repo }}/releases/download/{{ device_stalker_desired_version }}/checksum.sha256.sig"
        dest: "{{ device_stalker_checksum_signature_file }}"
        mode: "0640"
      register: device_stalker_download_signature
      until: device_stalker_download_signature is succeeded
      retries: 5
      delay: 2

    - name: Verify signature
      ansible.builtin.command: "signify -V -p /etc/signify/soerenschneider-github.pub -m {{ device_stalker_checksum_file }}"
      changed_when: false

    - name: Stop service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: stopped
      failed_when: false
      register: device_stalker_stopped_service

    - name: Copy binaries
      ansible.builtin.copy:
        src: "{{ device_stalker_download_dir }}/{{ device_stalker_full_filename }}"
        dest: "/usr/local/bin/{{ item }}"
        remote_src: true
        mode: 0755
        owner: root
        group: root
      with_items:
        - "{{ binary_name }}"
  always:
    - name: Delete downloaded files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "{{ device_stalker_download_dir }}"
      failed_when: false

    - name: Restart service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
      when: device_stalker_stopped_service is defined and device_stalker_stopped_service is changed
