---
- name: Including role
  ansible.builtin.include_role:
    name: haproxy
  tags: always

- name: Enable haproxy
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
  tags: haproxy

- name: Allow haproxy to bind to any port
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true
  tags: haproxy

- name: Set ca-cert file
  ansible.builtin.set_fact:
    ca_cert_file: "{% if ansible_facts['os_family'] == 'Debian' %}/etc/ssl/certs/ca-certificates.crt{% else %}/etc/ssl/certs/ca-bundle.crt{% endif %}"
  tags: haproxy

- name: Add configuration block
  ansible.builtin.blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: >
      frontend metrics
        bind {{ haproxy_listen_addr }}:8405 ssl crt /etc/haproxy/cert_{{ inventory_hostname }}.pem ca-file {{ pki_soerenschneider_ca_file }} verify optional
        mode http
        no log
        http-request use-service prometheus-exporter if { path /metrics } { ssl_c_used 1 } { ssl_c_verify 0 }
        stats uri /stats
        stats refresh 10s
        stats hide-version

      frontend media
        bind {{ haproxy_listen_addr }}:80
        mode http
        default_backend media

       frontend samba
         bind {{ haproxy_listen_addr }}:445
         mode tcp
         option tcplog
         default_backend smb

       frontend mpd
         bind {{ haproxy_listen_addr }}:6600
         mode tcp
         option tcplog
         default_backend mpd

       backend media
         option httpchk HEAD /media/

         server nas-{{ location }} nas.{{ location }}.{{ primary_network_domain }}:443 check inter 60s ssl ca-file {{ ca_cert_file }}
         # backup servers
         {% if location == 'dd' -%}
         server nas-pt nas.pt.{{ primary_network_domain }}:443 check inter 60s ssl ca-file {{ ca_cert_file }} backup weight 200
         server nas-ez nas.ez.{{ primary_network_domain }}:443 check inter 60s ssl ca-file {{ ca_cert_file }} backup weight 1
         {% elif location == 'ez' -%}
         server nas-pt nas.pt.{{ primary_network_domain }}:443 check inter 60s ssl ca-file {{ ca_cert_file }} backup weight 200
         server nas-dd nas.dd.{{ primary_network_domain }}:443 check inter 60s ssl ca-file {{ ca_cert_file }} backup weight 1
         {% elif location == 'pt' -%}
         server nas-dd nas.dd.{{ primary_network_domain }}:443 check inter 60s ssl ca-file {{ ca_cert_file }} backup weight 20
         server nas-ez nas.ez.{{ primary_network_domain }}:443 check inter 60s ssl ca-file {{ ca_cert_file }} backup weight 10
         {% endif -%}

       backend smb
         mode tcp
         timeout check 5000
         timeout server 30000
         timeout connect 5000
         server smb-{{ location }} nas.{{ location }}.{{ primary_network_domain }}:445 check
         # backup servers
         {% if location == 'dd' -%}
         server smb-pt nas.pt.{{ primary_network_domain }}:445 check backup weight 200
         server smb-ez nas.ez.{{ primary_network_domain }}:445 check backup weight 1
         {% elif location == 'ez' -%}
         server smb-pt nas.pt.{{ primary_network_domain }}:445 check backup weight 200
         server smb-dd nas.dd.{{ primary_network_domain }}:445 check backup weight 1
         {% elif location == 'pt' -%}
         server smb-dd nas.dd.{{ primary_network_domain }}:445 check backup weight 20
         server smb-ez nas.ez.{{ primary_network_domain }}:445 check backup weight 10
         {% endif -%}


       # highly available mpd library
       backend mpd
         mode tcp
         timeout check 5000
         timeout server 30000
         timeout connect 5000
         server mpd-{{ location }} nas.{{ location }}.{{ primary_network_domain }}:6600 check
         # backup servers
         {% if location == 'dd' -%}
         server mpd-pt nas.pt.{{ primary_network_domain }}:6600 check backup weight 200
         server mpd-ez nas.ez.{{ primary_network_domain }}:6600 check backup weight 1
         {% elif location == 'ez' -%}
         server mpd-pt nas.pt.{{ primary_network_domain }}:6600 check backup weight 200
         server mpd-dd nas.dd.{{ primary_network_domain }}:6600 check backup weight 1
         {% elif location == 'pt' -%}
         server mpd-dd nas.dd.{{ primary_network_domain }}:6600 check backup weight 20
         server mpd-ez nas.ez.{{ primary_network_domain }}:6600 check backup weight 10
         {% endif -%}
  notify: Restart haproxy
  tags: haproxy
