---
- name: Install MariaDB cluster
  hosts: auth
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    postgres_network: "{{ keycloak_docker_network }}"
  tasks:
    - name: Include role platform
      ansible.builtin.include_role:
        name: platform
      tags: always

    - name: "Run tasks haproxy.yml"
      ansible.builtin.include_tasks: tasks/haproxy.yml
      tags: always

    - name: Include role 'postgres'
      ansible.builtin.include_role:
        name: postgres
      tags: always

    - name: Include role 'keycloak'
      ansible.builtin.include_role:
        name: keycloak
      tags: always
