---
- name: Install MariaDB cluster
  hosts: auth
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: "Include role 'platform'"
      ansible.builtin.include_role:
        name: "platform"
      tags: always

    - name: Ensure passwordless sudo for sudo group in /etc/sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^%sudo\s+ALL=\(ALL:ALL\)\s+ALL'
        line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
        state: present
        create: no
        backup: yes
      tags: sudo

    - name: "Include role 'docker'"
      ansible.builtin.include_role:
        name: "docker"
      tags: always

    - name: "Install dependencies to run playbook autonomously via ansible-pull"
      ansible.builtin.package:
        name: "python3-jmespath"
      tags: [always, deps]

    - name: "Run tasks haproxy.yml"
      ansible.builtin.include_tasks: "tasks/haproxy.yml"
      tags: always

    - name: "Create docker network"
      community.docker.docker_network:
        name: "{{ keycloak_docker_network }}"
      tags: [docker, keycloak, postgres]

    - name: "Include role 'mariadb_cluster'"
      ansible.builtin.include_role:
        name: "mariadb_cluster"
      tags: always

    - name: "Include role 'keycloak'"
      ansible.builtin.include_role:
        name: "keycloak"
      tags: always

    - name: "Include role 'ansible_node'"
      ansible.builtin.include_role:
        name: "ansible_node"
      tags: always
