---
- name: "Set variables"
  ansible.builtin.set_fact:
    navidrome_local_binary: ""
    navidrome_installed_version: ""
    navidrome_desired_version: "{{ navidrome_version | default('') }}"
    navidrome_download_archive: ""
    navidrome_download_signature: ""
    navidrome_stopped_service: ""
    navidrome_github_release: ""
    navidrome_go_os: ""
    navidrome_go_arch: ""
    navidrome_checksum_signature_file: ""
    navidrome_checksum_file: ""
    navidrome_full_filename: ""
    navidrome_release_checksum: ""
  tags: [navidrome, navidrome-install, deps]

- name: Check for existing binary
  ansible.builtin.stat:
    path: /usr/local/bin/{{ binary_name }}
  register: navidrome_local_binary
  tags: [navidrome, navidrome-install, deps]

- name: Check installed version
  when: navidrome_local_binary.stat.exists
  tags: [navidrome, navidrome-install, deps]
  block:
    - name: Check installed version
      ansible.builtin.shell: set -o pipefail && /usr/local/bin/{{ binary_name }} --version | awk '{print $1}'
      register: navidrome_installed_version
      changed_when: false

    - name: Register local version
      ansible.builtin.set_fact:
        navidrome_installed_version: "v{{ navidrome_installed_version.stdout }}"
      changed_when: false

    - name: Print debug information
      ansible.builtin.debug:
        msg: "Installed version: {{ navidrome_installed_version }}"
      changed_when: false

- name: Fetch latest release information from github
  when: navidrome_desired_version is not defined or not navidrome_desired_version
  tags: [navidrome, navidrome-install, deps]
  block:
    - name: Print debug information
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ github_repo }}/releases/latest
        return_content: true
      register: navidrome_github_release
      retries: 3
      delay: 5
      until: navidrome_github_release is not failed

    - name: Set github release
      ansible.builtin.set_fact:
        navidrome_desired_version: "{{ navidrome_github_release.json.tag_name }}"
      changed_when: false

    - name: Print latest GitHub version
      ansible.builtin.debug:
        msg: "Latest GitHub version: {{ navidrome_desired_version }}"
      changed_when: false

- name: "Download artifacts"
  when: not navidrome_local_binary.stat.exists or navidrome_desired_version != navidrome_installed_version
  tags: [navidrome, navidrome-install, deps]
  block:
    - name: Generate temp dir
      become: false
      ansible.builtin.tempfile:
        state: directory
        suffix: "{{ binary_name }}"
      register: navidrome_download_dir

    - name: Set vars for generating download link
      ansible.builtin.set_fact:
        navidrome_go_os: "{{ ansible_system | lower }}"
        navidrome_go_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'armv6' if ansible_architecture == 'armv6l' else 'armv7' if ansible_architecture == 'armv7l' else 'arm64' if ansible_architecture == 'aarch64' }}"
        navidrome_download_dir: "{{ navidrome_download_dir.path }}"
        navidrome_extraction_dir: "{{ navidrome_download_dir.path }}/{{ binary_name }}"
      changed_when: false

    - name: Set filenames
      ansible.builtin.set_fact:
        navidrome_checksum_file: "{{ navidrome_download_dir }}/{{ binary_name }}_checksums.txt"
        navidrome_full_filename: "{{ binary_name }}_{{ navidrome_desired_version[1:] }}_{{ navidrome_go_os }}_{{ navidrome_go_arch }}.tar.gz"
      changed_when: false

    - name: Get checksum for archive
      ansible.builtin.set_fact:
        navidrome_release_checksum: "{{ item.split(' ')[0] }}"
      when: [navidrome_full_filename in item, (not navidrome_local_binary.stat.exists or navidrome_installed_version != navidrome_desired_version)]
      with_items: ["{{ lookup('url', 'https://github.com/{{ github_repo }}/releases/download/' + navidrome_desired_version + '/navidrome_checksums.txt', wantlist=True) | list }}"]

    - name: Download binary
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/{{ github_repo }}/releases/download/{{ navidrome_desired_version }}/{{ navidrome_full_filename }}"
        dest: "{{ navidrome_download_dir }}/{{ navidrome_full_filename }}"
        checksum: sha256:{{ navidrome_release_checksum }}
        mode: "0640"
      register: navidrome_download_archive
      until: navidrome_download_archive is succeeded
      retries: 5
      delay: 2

    - name: Download release checksum
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/{{ github_repo }}/releases/download/{{ navidrome_desired_version }}/navidrome_checksums.txt"
        dest: "{{ navidrome_checksum_file }}"
        mode: "0640"
      register: navidrome_download_signature
      until: navidrome_download_signature is succeeded
      retries: 5
      delay: 2

    - name: Stop service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: stopped
      failed_when: false
      register: navidrome_stopped_service

    - name: Copy binaries
      ansible.builtin.copy:
        src: "{{ navidrome_download_dir }}/{{ navidrome_full_filename }}"
        dest: /usr/local/bin/{{ item }}
        remote_src: true
        mode: "0755"
        owner: root
        group: root
      with_items: ["{{ binary_name }}"]

    - name: Unpack binaries from archive
      become: false
      ansible.builtin.unarchive:
        src: "{{ navidrome_download_dir }}/{{ navidrome_full_filename }}"
        dest: "{{ navidrome_download_dir }}"
        creates: "{{ navidrome_download_dir }}/navidrome"
        remote_src: true
      check_mode: false

    - name: Copy binaries
      ansible.builtin.copy:
        src: "{{ navidrome_download_dir }}/navidrome"
        dest: /usr/local/bin/{{ item }}
        remote_src: true
        mode: "0755"
        owner: root
        group: root
      with_items: ["{{ binary_name }}"]

  always:
    - name: Delete downloaded files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items: ["{{ navidrome_download_dir }}"]
      failed_when: false

    - name: Restart service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
      when: navidrome_stopped_service is defined and navidrome_stopped_service is changed
