---
- name: Create mountpoint target path
  ansible.builtin.file:
    path: "{{ disk.mountpoint }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  notify: [Mount_all_disks]
  tags: [disk]

- name: Add fstab entry for disk
  ansible.posix.mount:
    path: "{{ disk.mountpoint }}"
    src: "{{ disk.partition }}"
    fstype: "{{ disk.fs }}"
    opts: auto,nofail,noatime
    state: present
  notify: [Mount_all_disks]
  tags: [disk]

- name: Create gocryptfs mountpoints
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ gocryptfs_mounts | default([]) }}"
  tags: disk
