---
- name: Install jq
  ansible.builtin.package:
    name: jq
  tags: [media, remote_move]

- name: Copy script to sync opus collection
  ansible.builtin.template:
    src: templates/sync-opus-collection.j2
    dest: /usr/local/bin/sync-opus-collection
    owner: root
    group: root
    mode: "0755"
  tags: [media, music]

- name: Add SSH keys
  when: fileserver_mode == 'active'
  tags: [media, remote_move]
  become_user: "{{ nas_media_user }}"
  become: true
  block:
    - name: Make sure ssh dir exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        owner: "{{ nas_media_user }}"
        group: "{{ nas_media_user }}"
        mode: "0700"

    - name: Set public key
      ansible.builtin.copy:
        dest: ~/.ssh/id_ed25519.pub
        content: "{{ fetcharr_credentials.pub }}\n"
        owner: "{{ nas_media_user }}"
        group: "{{ nas_media_user }}"
        mode: "0644"

    - name: Set private key
      ansible.builtin.copy:
        dest: ~/.ssh/id_ed25519
        content: "{{ fetcharr_credentials.priv }}\n"
        owner: "{{ nas_media_user }}"
        group: "{{ nas_media_user }}"
        mode: "0600"

    - name: Add ssh config entry for remotemove host
      ansible.builtin.copy:
        content: |
          Host {{ fetcharr_remote_host }}
            Port 2222
        dest: "/home/{{ nas_media_user }}/.ssh/config"
        owner: "{{ nas_media_user }}"
        group: "{{ nas_media_user }}"
        mode: "0600"
      when: false

- name: Add remote host public key to known_hosts
  ansible.builtin.known_hosts:
    name: "{{ fetcharr_remote_host }}"
    hash_host: false
    key: "{{ item.key }}"
    state: present
  with_items: "{{ ssh_known_hosts | selectattr('name', 'in', [fetcharr_remote_host]) | list }}"
  when: fileserver_mode == 'active'
  become_user: "soeren"
  tags: [media, remote_move]
