
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  #config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.vault_password_file = "~/bin/open-ansible-vault.sh"
    ansible.playbook = "vps.yml"
    ansible.tags = "wireguard-config"
    ansible.groups = {
      "doh" => ["default"]
    }
  end
end

