---
- name: Setup MPD servers
  hosts: jukebox
  become: true
  strategy: free
  tasks:
    - name: Include role platform
      ansible.builtin.include_role:
        name: platform
      tags: always

    - name: Load hifiberry driver
      ansible.builtin.include_tasks:
        file: tasks/hifiberry.yml
      tags: [dac, hifiberry]

    - name: Include role mpd
      ansible.builtin.include_role:
        name: mpd
      tags: always

  handlers:
    - name: Reboot load hifiberry driver
      ansible.builtin.reboot: {}
      tags: [hifiberry, dac]
