---
- name: Set strong key exchange algorithms
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^KexAlgorithms
    line: KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
  notify: Restart_sshd
  tags: [ssh, base]

- name: Set strong ciphers
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^Ciphers
    line: Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
  notify: Restart_sshd
  tags: [ssh, base]

- name: Set strong MACs
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^MACs
    line: MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
  notify: Restart_sshd
  tags: [ssh, base]

- name: Set allowed protocol to version 2
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^#?Protocol
    line: Protocol 2
  notify: Restart_sshd
  tags: [ssh, base]

- name: Disable DNS reverse lookups
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^#?UseDNS
    line: UseDNS no
  notify: Restart_sshd
  tags: [ssh, base]

- name: Disable X11 forwarding
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^#?X11Forwarding
    line: X11Forwarding no
  notify: Restart_sshd
  tags: [ssh, base]

- name: Lower login grace time to 30s
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^#?LoginGraceTime
    line: LoginGraceTime 30s
  notify: Restart_sshd
  tags: [ssh, base]
