---
- name: Create alertmanager system group
  ansible.builtin.group:
    name: "{{ alertmanager_group }}"
    system: true
    state: present
  tags: [monitoring, alertmanager, alertmanager-install]

- name: Create alertmanager system user
  ansible.builtin.user:
    name: "{{ alertmanager_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ alertmanager_user }}"
    createhome: false
  tags: [monitoring, alertmanager, alertmanager-install]

- name: Create alertmanager data directory
  ansible.builtin.file:
    path: "{{ alertmanager_db_dir }}"
    state: "directory"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
    mode: "0755"
  tags: [monitoring, alertmanager, alertmanager-install]

- name: Create alertmanager configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
    mode: "0770"
  with_items:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_config_dir }}/templates"
    - "{{ alertmanager_db_dir }}"
  tags: [monitoring, alertmanager, alertmanager-install]

- name: Include tasks
  ansible.builtin.include_tasks: install-github.yml
  tags: [monitoring, alertmanager, alertmanager-install]
