---
- name: Create autobackup system group
  ansible.builtin.group:
    name: "{{ autobackup_group }}"
    system: true
    state: present
  tags: [autobackup, autobackup-configure]

- name: Create autobackup system user
  ansible.builtin.user:
    name: "{{ autobackup_user }}"
    group: "{{ autobackup_group }}"
  tags: [autobackup, autobackup-configure]

- name: Create backup dir
  ansible.builtin.file:
    path: "{{ autobackup_backups_dir }}"
    state: directory
    owner: "{{ autobackup_user }}"
    group: "{{ autobackup_backups_group }}"
    mode: "02770"
  tags: [autobackup, autobackup-configure]

- name: Create cron entry to automatically perform backup
  ansible.builtin.cron:
    name: Run autobackup
    hour: "{{ autobackup_cron_hour }}"
    minute: "{{ autobackup_cron_minute }}"
    user: "{{ autobackup_user }}"
    job: /usr/local/bin/autobackup
    state: "{{ 'present' if autobackup_cron_enabled else 'absent' }}"
  tags: [autobackup, autobackup-configure]
