---
- name: Restart openbao
  ansible.builtin.service:
    name: openbao
    state: restarted

- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
    daemon_reload: true
