---
- name: Install vault-unsealer
  hosts: vault-unsealer
  become: true
  tasks:
    - name: "Run role vault_unsealer"
      ansible.builtin.include_role:
        name: vault_unsealer
      tags: always

    - name: "Run role platform"
      ansible.builtin.include_role:
        name: platform
      tags: always
