---
- name: Including role
  ansible.builtin.include_role:
    name: haproxy
  tags: always

- name: Add configuration block
  ansible.builtin.blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      listen stats
          bind *:8405 ssl crt {{ acmevault_pem_file }} ca-file {{ pki_soerenschneider_ca_file }} verify required
          mode http
          # only allow the following CNs
          http-request deny if !{ ssl_c_s_dn(cn) -f {{ haproxy_allowed_scrapers_cns_file }} }

          http-request use-service prometheus-exporter if { path /metrics }

          stats enable
          stats hide-version
          stats realm Haproxy\ Statistics

      frontend cadvisor_exporter
          bind *:9080 ssl crt {{ acmevault_pem_file }} ca-file {{ pki_soerenschneider_ca_file }} verify required
          mode http
          # only allow the following CNs
          http-request deny if !{ ssl_c_s_dn(cn) -f {{ haproxy_allowed_scrapers_cns_file }} }

          default_backend cadvisor_exporter

      frontend mysqld_exporter
          bind *:9144 ssl crt {{ acmevault_pem_file }} ca-file {{ pki_soerenschneider_ca_file }} verify required
          mode http
          # only allow the following CNs
          http-request deny if !{ ssl_c_s_dn(cn) -f {{ haproxy_allowed_scrapers_cns_file }} }

          default_backend mysqld_exporter

      frontend node_exporter
          bind *:9443 ssl crt {{ acmevault_pem_file }} ca-file {{ pki_soerenschneider_ca_file }} verify required
          mode http
          # only allow the following CNs
          http-request deny if !{ ssl_c_s_dn(cn) -f {{ haproxy_allowed_scrapers_cns_file }} }

          default_backend node_exporter

      frontend https_in
        bind *:443 ssl crt {{ acmevault_pem_file }} alpn h2,http/1.1
        mode http
        option forwardfor
        default_backend be_keycloak

      backend be_keycloak
        mode http
        balance roundrobin

        # Insert a cookie so sessions are sticky (useful if your Keycloak cluster isn't fully state-shared)
        cookie KC insert indirect nocache maxidle 30m maxlife 4h

        # servers (plain HTTP) - change IPs and ports to your Keycloak nodes
        server kc1 127.0.0.1:8080 check

        # Headers Keycloak expects:
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        http-request set-header Host %[req.hdr(Host)]

      backend cadvisor_exporter
        option httpchk
        server node_exporter 127.0.0.1:{{ docker_cadvisor_port }} check inter 30s

      backend mysqld_exporter
        option httpchk
        server node_exporter 127.0.0.1:9104 check inter 30s

      backend node_exporter
        option httpchk
        server node_exporter 127.0.0.1:9100 check inter 5m

      listen galera
        bind *:3307
        balance source
        mode tcp
        option tcpka
        option tcplog

        server mariadb-{{ location | default('0') }} localhost:3306 check
        {% for node in groups['dbs'] -%}
        {%- if node != inventory_hostname -%}
        server mariadb-{{ hostvars[node].location }}-{{ loop.index }} {{ node }}:3306 check backup
        {% endif -%}
        {% endfor -%}

  notify: Restart haproxy
  tags: [haproxy]
