---
- name: Create mariadb initdb scripts
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ mariadb_cluster_initdb_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_user }}"
    mode: "0740"
  with_fileglob:
    - "templates/mariadb-initdb/*.j2"
  tags: [mariadb, mariadb-configure]

- name: Create mariadb initdb scripts from playbook templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ mariadb_cluster_initdb_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_user }}"
    mode: "0740"
  with_fileglob:
    - "{{ playbook_dir }}/templates/mariadb-initdb/*.j2"
  tags: [mariadb, mariadb-configure]

- name: Create env file
  ansible.builtin.copy:
    content: |
      MARIADB_ROOT_PASSWORD={{ mariadb_cluster_root_password }}
      MARIADB_CHARACTER_SET=utf8mb4
      MARIADB_COLLATE=utf8mb4_unicode_520_ci
      TZ=UTC
    dest: "{{ mariadb_cluster_base_dir }}/env"
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0440"
  tags: [mariadb, mariadb-configure]

- name: Add my.cnf
  ansible.builtin.copy:
    content: |
      [client]
      user = {{ mariadb_cluster_root_user }}
      password = {{ mariadb_cluster_root_password }}
      [mariadb]
      ssl_cert = /certs/tls.crt
      ssl_key = /certs/tls.key
      require_secure_transport = ON
      binlog_format = ROW
      default_storage_engine=InnoDB
      innodb_autoinc_lock_mode=2
      [galera]
      wsrep_on = ON
      wsrep_cluster_name = {{ mariadb_cluster_galera_cluster_name }}
      wsrep_provider = /usr/lib/galera/libgalera_smm.so
      wsrep_sst_method=mariabackup
      wsrep_sst_auth=sst_user:{{ mariadb_cluster_replication_password }}
      wsrep_node_incoming_address={{ inventory_hostname }}
      wsrep_node_address={{ inventory_hostname }}
      wsrep-node-name={{ inventory_hostname }}
      {% if mariadb_cluster_preferred_donors | default([]) | length > 0 %}
      # NOTE: the comma at the end is not a typo, see https://fromdual.com/define-preferred-sst-donor-for-galera-cluster
      wsrep_sst_donor={{ mariadb_cluster_preferred_donors | join(',') }},
      {% endif %}
      wsrep_provider_options=gcache.size=512M;socket.ssl=yes;socket.ssl_ca=/certs/wsrep-ca.crt;socket.ssl_cert=/certs/wsrep.crt;socket.ssl_key=/certs/wsrep.key;;ist.recv_addr={{ inventory_hostname }}:4568;ist.recv_bind=0.0.0.0:4568;
      [sst]
      tca=/certs/sst-ca.crt
      tcert=/certs/sst.crt
      encrypt=2
      [mariabackup]
      ssl-verify-server-cert = false
    dest: "{{ mariadb_cluster_base_dir }}/my.cnf"
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0440"
  register: mariadb_cluster_set_config
  tags: [mariadb, mariadb-configure]
