---
- name: Create mariadb group
  ansible.builtin.group:
    name: "{{ mariadb_cluster_group }}"
    system: true
  register: mariadb_cluster_install_group
  tags: [mariadb, exporter, mariadb-install]

- name: Create mariadb user
  ansible.builtin.user:
    name: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    system: true
  register: mariadb_cluster_install_user
  tags: [mariadb, exporter, mariadb-install]

- name: Create mariadb dir
  ansible.builtin.file:
    path: "{{ mariadb_cluster_base_dir }}"
    state: directory
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0770"
  register: mariadb_cluster_install_base_dir
  tags: [mariadb, mariadb-install]

- name: Create mariadb storage dir
  ansible.builtin.file:
    path: "{{ mariadb_cluster_storage_dir }}"
    state: directory
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0770"
  register: mariadb_cluster_install_storage_dir
  tags: [mariadb, mariadb-install]

- name: Create mariadb certs dir
  ansible.builtin.file:
    path: "{{ mariadb_cluster_certs_dir }}"
    state: directory
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0770"
  register: mariadb_cluster_install_certs_dir
  tags: [mariadb, mariadb-install]

- name: Create mariadb initdb dir
  ansible.builtin.file:
    path: "{{ mariadb_cluster_initdb_dir }}"
    state: directory
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0770"
  register: mariadb_cluster_install_initdb_dir
  tags: [mariadb, mariadb-install]

- name: Pull mariadb docker image
  community.docker.docker_image_pull:
    name: "{{ mariadb_cluster_image }}"
  register: mariadb_cluster_install_container_image
  tags: [mariadb, mariadb-install]

- name: Determine if mariadb installation changed
  ansible.builtin.set_fact:
    mariadb_cluster_install_changed: >-
      {{ mariadb_cluster_install_group.changed
         or mariadb_cluster_install_user.changed
         or mariadb_cluster_install_base_dir.changed
         or mariadb_cluster_install_storage_dir.changed
         or mariadb_cluster_install_certs_dir.changed
         or mariadb_cluster_install_initdb_dir.changed
         or mariadb_cluster_install_container_image.changed }}
  tags: [mariadb, mariadb-configure]
