---
- name: Create mariadb group
  ansible.builtin.group:
    name: "{{ mariadb_cluster_group }}"
    system: true
  tags: [mariadb, exporter, mariadb-install]

- name: Create mariadb user
  ansible.builtin.user:
    name: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    system: true
  tags: [mariadb, exporter, mariadb-install]

- name: Create mariadb dir
  ansible.builtin.file:
    path: "{{ mariadb_cluster_base_dir }}"
    state: directory
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0770"
  tags: [mariadb, mariadb-install]

- name: Create mariadb storage dir
  ansible.builtin.file:
    path: "{{ mariadb_cluster_storage_dir }}"
    state: directory
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0770"
  tags: [mariadb, mariadb-install]

- name: Create mariadb certs dir
  ansible.builtin.file:
    path: "{{ mariadb_cluster_certs_dir }}"
    state: directory
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0770"
  tags: [mariadb, mariadb-install]

- name: Create mariadb initdb dir
  ansible.builtin.file:
    path: "{{ mariadb_cluster_initdb_dir }}"
    state: directory
    owner: "{{ mariadb_cluster_user }}"
    group: "{{ mariadb_cluster_group }}"
    mode: "0770"
  tags: [mariadb, mariadb-install]

- name: Pull mariadb docker image
  community.docker.docker_image_pull:
    name: "{{ mariadb_cluster_image }}"
  tags: [mariadb, mariadb-install]
