---
- name: Install keepalived
  ansible.builtin.package:
    name:
      - keepalived
  tags: [keepalived]

- name: Update keepalived config
  ansible.builtin.template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    owner: "root"
    mode: "0640"
  when: keepalived_vrrp_instances | default([]) | length > 0
  notify: "Restart keepalived"
  tags: [keepalived]

- name: Allow VRRP (protocol 112) in UFW before.rules
  ansible.builtin.lineinfile:
    path: /etc/ufw/before.rules
    insertafter: '^\*filter'
    line: '-A ufw-before-input -p 112 -j ACCEPT'
    state: present
  when: keepalived_vrrp_instances | default([]) | length > 0
  notify: "Restart keepalived"
  tags: [keepalived]

- name: "Enable/disable keepalived"
  ansible.builtin.systemd:
    name: "keepalived"
    enabled: "{% if keepalived_vrrp_instances | default([]) | length > 0 %}true{% else %}false{% endif %}"
    state: "{% if keepalived_vrrp_instances | default([]) | length > 0 %}started{% else %}stopped{% endif %}"
  tags: [keepalived]
