---
- name: Including role 'baseline'
  ansible.builtin.include_role:
    name: baseline
  tags: always

- name: Including role 'ssh'
  ansible.builtin.include_role:
    name: ssh
  tags: always

- name: Including role 'node_exporter'
  ansible.builtin.include_role:
    name: node_exporter
  tags: always

- name: Including role 'sc_agent'
  ansible.builtin.include_role:
    name: sc_agent
  tags: always

- name: Including role 'automatic_sysupdates'
  ansible.builtin.include_role:
    name: automatic_sysupdates
  tags: always

- name: Including role 'vault_approle'
  ansible.builtin.include_role:
    name: vault_approle
  when: false and vault_approles | default([]) | length > 0
  tags: always

- name: Including role 'vector'
  ansible.builtin.include_role:
    name: vector
  when: ansible_architecture != 'armv6l'
  tags: always
