---
- name: Install dependencies
  ansible.builtin.package:
    name: [python3-iso8601, python3-requests]
  tags: [vault-approle, vault-approle-install]

- name: Fetch scripts repo
  ansible.builtin.git:
    repo: https://github.com/soerenschneider/scripts
    dest: /opt/scripts
    version: main
  tags: [vault-approle, vault-approle-install]

- name: Copy vault_approle_cli script
  ansible.builtin.file:
    src: /opt/scripts/vault/vault-approle-cli.py
    dest: /usr/local/bin/vault-approle-cli
    state: link
    owner: root
    mode: "0555"
  tags: [vault-approle, vault-approle-install]

- name: Create systemd timer and service
  ansible.builtin.template:
    src: vault-approle@.{{ item }}.j2
    dest: /etc/systemd/system/vault-approle@.{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items: [service, timer]
  register: _vault_approle_systemd_units
  tags: [vault-approle, vault-approle-install]

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: _vault_approle_systemd_units.changed | default(true)  # noqa: no-handler
  tags: [vault-approle, vault-approle-install]

- name: Create config dir
  ansible.builtin.file:
    path: /etc/vault-approle
    state: directory
    owner: root
    group: root
    mode: "0700"
  tags: [vault-approle, vault-approle-install]

- name: Rotate secret
  ansible.builtin.include_tasks: run.yml
  with_items: "{{ vault_approles }}"
  when: lookup('env', 'VAULT_TOKEN') | length > 0
  tags: [vault-approle, vault-approle-install, vault-approle-rotate]
