---
- name: Run mysqld exporter
  community.docker.docker_container:
    name: mysqld-exporter
    image: "{{ mysqld_exporter_image }}"
    user: "{{ _mariadb_user_string }}"
    restart_policy: always
    networks:
      - name: mariadb-cluster
    env:
      MYSQLD_EXPORTER_PASSWORD: "{{ mysqld_exporter_password }}"
    command: |
      --mysqld.address={{ mariadb_container_name }}:3306
      --mysqld.username=exporter
      --tls.insecure-skip-verify
      --log.level=debug
    ports: [0.0.0.0:9104:9104]
  tags: [mariadb, exporter, mysql]
