---
- name: Disable onboard sound
  ansible.builtin.lineinfile:
    path: "/boot/firmware/config.txt"
    regexp: '^\s*#?\s*dtparam=audio=.*$'
    line: "dtparam=audio=off"
    insertbefore: "BOF"
    firstmatch: true
  when: hifiberry_driver | default('') | length > 0
  notify: Reboot load hifiberry driver
  tags: [hifiberry, dac]

- name: Enable hifiberry driver
  ansible.builtin.blockinfile:
    path: "/boot/firmware/config.txt"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: hifiberry"
    block: |
      [all]
      dtoverlay=hifiberry-{{ hifiberry_driver }}
  when: hifiberry_driver | default('') | length > 0
  notify: Reboot load hifiberry driver
  tags: [hifiberry, dac]