---
- name: Including tasks
  ansible.builtin.include_tasks: install.yml
  tags: [mosquitto, mosquitto-install]

- name: Including tasks
  ansible.builtin.include_tasks: configure.yml
  tags: [mosquitto, mosquitto-configure]

- name: Including tasks
  ansible.builtin.include_tasks: certbot.yaml
  tags: [mosquitto, mosquitto-configure, mosquitto-certbot]

- name: Including tasks
  ansible.builtin.include_tasks: exporter.yml
  when: mosquitto_exporter_install
  tags: [mosquitto, mosquitto_exporter]
