---
- name: Install desktop
  hosts: localhost
  become: false
  vars:
    vault_configure_server: false
    inventory_path: "{{ lookup('env', 'ANSIBLE_INVENTORY') | dirname }}"
    user_home: "{{ ansible_facts['env']['HOME'] }}"
  tasks:
    - name: "Determine hostname (without ansible facts)"
      ansible.builtin.command: "hostname"
      register: "_hostname_output"
      changed_when: false
      tags: always

    - name: "Set hostname and inventory_hostname"
      ansible.builtin.set_fact:
        hostname: "{{ _hostname_output.stdout }}"  # noqa: var-naming[read-only]
        inventory_hostname: "{{ _hostname_output.stdout }}"  # noqa: var-naming[read-only]
      become: true
      tags: always

    - name: "Print hostname"
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"
      tags: always

    - name: "Load general settings"
      ansible.builtin.include_vars:
        file: "settings/general.yaml"
      tags: always

    - name: "Load host-based settings"
      ansible.builtin.include_vars:
        file: "settings/host-{{ hostname }}.yaml"
      ignore_errors: true
      register: ignore_errors_register
      tags: always

    - name: "Include task repos"
      ansible.builtin.include_tasks: "tasks/repos.yml"
      tags: always

    - name: "Include task dirs"
      ansible.builtin.include_tasks: "tasks/dirs.yml"
      tags: always

    - name: "Include task zsh"
      ansible.builtin.include_tasks: "tasks/zsh.yml"
      tags: always

    - name: "Install packages"
      when: ansible_facts["os_family"] == "RedHat"
      block:
        - name: "Include task rpmfusion"
          ansible.builtin.include_tasks: tasks/rhel-rpmfusion.yml
          tags: always

        - name: "Include task flatpak"
          ansible.builtin.include_tasks: tasks/install-flatpak.yaml
          tags: always

        - name: "Include task auto_updates"
          ansible.builtin.include_tasks: tasks/rhel-auto-updates.yml
          tags: always

        - name: "Include task go"
          ansible.builtin.include_tasks: tasks/install-go.yaml
          tags: always

        - name: "Include task go_tools"
          ansible.builtin.include_tasks: tasks/install-go-tools.yaml
          tags: always

    - name: "Configure Linux services"
      when: ansible_facts['system'] == "Linux"
      ansible.builtin.include_tasks: "tasks/services.yaml"
      tags: always

    - name: Add private CA
      ansible.builtin.copy:
        content: "{{ pki_soerenschneider_ca_crt }}"
        dest: "{{ pki_soerenschneider_ca_file }}"
        owner: root
        group: "{% if ansible_system == 'Linux' %}root{% else %}wheel{% endif %}"
        mode: "0644"
      when: ansible_facts['system'] == "Linux"
      tags: [base, pki]
