---
- name: Add minio group
  ansible.builtin.group:
    name: "{{ minio_group }}"
  tags: [minio, minio-install]

- name: Add minio user
  ansible.builtin.user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: true
    shell: /usr/sbin/nologin
  tags: [minio, minio-install]

- name: Add base dir
  ansible.builtin.file:
    path: "{{ minio_base_dir }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0700"
  tags: [minio, minio-install]

- name: Add volume dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0700"
  with_items: "{{ minio_volumes }}"
  tags: [minio, minio-install]

- name: Add minio config
  ansible.builtin.template:
    src: minio.conf.j2
    dest: /etc/minio.conf
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0600"
  notify: restart minio
  tags: [minio, minio-install]

- name: Add minio systemd file
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    owner: root
    group: root
    mode: "0644"
  notify: restart minio
  tags: [minio, minio-install]

- name: Enable/disable minio
  ansible.builtin.systemd:
    name: minio
    enabled: "{% if minio_disabled | default(False) %}false{% else %}true{% endif %}"
    state: "{% if minio_disabled | default(False) %}stopped{% else %}started{% endif %}"
    daemon_reload: true
  tags: [minio, minio-install]

- name: Start minio
  ansible.builtin.systemd:
    name: minio
    state: started
  tags: [minio, minio-install]
