---
- name: Restart chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted

- name: "Restart journald"
  ansible.builtin.systemd:
    name: "systemd-journald"
    state: "restarted"
