---
- name: Restart chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted

- name: "Restart journald"
  ansible.builtin.systemd:
    name: "systemd-journald"
    state: "restarted"

- name: "remount filesystems"
  ansible.posix.mount:
    path: "{{ item }}"
    state: remounted
  with_items: "{{ ansible_mounts | selectattr('fstype', 'match', '^(ext[234]|xfs|btrfs)$') | map(attribute='mount') | list }}"
  listen: "remount filesystems"
