---
- name: "Setup OpenBAO cluster"
  hosts: "openbao"
  become: true
  tasks:
    - name: "Print user info"
      ansible.builtin.debug:
        msg: "User is: {{ ansible_user }}"

    - name: "Run role platform"
      ansible.builtin.include_role:
        name: "platform"
      tags: always

    - name: "Run tasks haproxy.yml"
      ansible.builtin.include_tasks: "tasks/haproxy.yml"
      tags: "always"

    - name: "Run role certbot"
      ansible.builtin.include_role:
        name: "certbot"
      tags: "always"

    - name: "Run tasks haproxy.yml"
      ansible.builtin.include_tasks: "tasks/haproxy.yml"
      tags: "always"

    - name: "Run role openbao"
      ansible.builtin.include_role:
        name: "openbao"
      tags: always

    - name: "Copy cert hook"
      ansible.builtin.template:
        src: "openbao-cert-hook.sh.j2"
        dest: "/etc/letsencrypt/renewal-hooks/post/openbao-cert-hook.sh"
        owner: "root"
        group: "root"
        mode: "0755"
      notify: "Run letsencrypt hook for openbao"
      tags: [openbao, openbao-cert]

  handlers:
    - name: "Run letsencrypt hook for openbao"
      changed_when: false
      ansible.builtin.command: "/etc/letsencrypt/renewal-hooks/post/openbao-cert-hook.sh"
