---
- name: Install docker on Debian 12
  ansible.builtin.package:
    name: [docker.io, python3-docker]
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version == "12"
  tags: [docker]

- name: Install docker on Debian 13
  ansible.builtin.package:
    name:
      - docker.io
      - docker-cli
      - python3-docker
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version == "13"
  tags: [docker]

- name: Create or update Docker daemon config for log rotation
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "3m",
          "max-file": "3"
        }
      }
    owner: root
    group: root
    mode: '0644'
  tags: [docker]

- name: Add cleanup systemd units
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: "0644"
  register: _docker_prune_svc
  with_items: [docker-prune.service, docker-prune.timer]
  tags: [docker]

- name: Enable prune timer and service
  ansible.builtin.systemd:
    name: "{{ item }}"
    daemon_reload: true
    enabled: true
    state: started
  with_items: [docker-prune.service, docker-prune.timer]
  tags: [docker]

- name: Start cAdvisor container
  community.docker.docker_container:
    name: cadvisor
    image: "gcr.io/cadvisor/cadvisor:{{ docker_cadvisor_version }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "127.0.0.1:{{ docker_cadvisor_port }}:{{ docker_cadvisor_port }}"
    command:
      - "-store_container_labels=false"
      - "-port={{ docker_cadvisor_port }}"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  when: docker_enable_cadvisor
  tags: [docker, deps, cadvisor]
