---
- name: Install docker
  ansible.builtin.package:
    name: [docker.io, python3-docker]
  when: [ansible_os_family == "Debian"]
  tags: [docker]

- name: Add cleanup systemd units
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: "0644"
  register: _docker_prune_svc
  with_items: [docker-prune.service, docker-prune.timer]
  tags: [docker]

- name: Enable prune timer
  ansible.builtin.systemd:
    name: docker-prune.timer
    daemon_reload: true
    enabled: true
    state: started
  tags: [docker]
