---
- name: Install dependencies
  ansible.builtin.dnf:
    name: [python3-netifaces, python3-pygit2, python3-psutil, python3-requests, python3-upm]
  tags: [sway, bumblebee_status]

- name: Checkout bumblebee
  become: false
  ansible.builtin.git:
    repo: https://github.com/tobi-wan-kenobi/bumblebee-status.git
    dest: "{{ sway_sw_dir }}/bumblebee-status"
    version: main
  tags: [sway, bumblebee_status]
