---
- name: grim | Install deps
  ansible.builtin.dnf:
    name: [cairo, libjpeg]
  tags: [sway, grim]

- name: grim | Checkout grim
  become: false
  ansible.builtin.git:
    repo: https://github.com/emersion/grim.git
    dest: "{{ sway_sw_dir }}/grim"
    version: "{{ sway_grim_version }}"
  register: git_clone
  tags: [sway, grim]

- name: Grim | Meson build
  environment:
    PKG_CONFIG_PATH: /usr/local/lib64/pkgconfig
  ansible.builtin.command: meson build -Dsysconfdir=/etc
  changed_when: false
  become: false
  args:
    chdir: "{{ sway_sw_dir }}/grim"
    #  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, grim]

- name: Grim | Ninja build
  ansible.builtin.command: ninja -C build
  become: false
  args:
    chdir: "{{ sway_sw_dir }}/grim"
    #  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  changed_when: true
  tags: [sway, grim]

- name: Grim | Ninja install
  ansible.builtin.command: ninja -C build install
  args:
    chdir: "{{ sway_sw_dir }}/grim"
    #  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  changed_when: true
  tags: [sway, grim]
