---
- name: Install deps
  ansible.builtin.dnf:
    name: [gdk-pixbuf2-devel, cairo-devel, dbus-devel]
  tags: [sway, mako]

- name: Checkout mako
  become: false
  ansible.builtin.git:
    repo: https://github.com/emersion/mako.git
    dest: "{{ sway_sw_dir }}/mako"
    version: "{{ sway_mako_version }}"
  register: git_clone
  tags: [sway, mako]

- name: Meson build
  ansible.builtin.command: meson build -Dsysconfdir=/etc
  changed_when: true
  become: false
  args:
    chdir: "{{ sway_sw_dir }}/mako"
  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, mako]

- name: Ninja build
  ansible.builtin.command: ninja -C build
  changed_when: true
  become: false
  args:
    chdir: "{{ sway_sw_dir }}/mako"
  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, mako]

- name: Ninja install
  ansible.builtin.command: ninja -C build install
  changed_when: true
  args:
    chdir: "{{ sway_sw_dir }}/mako"
  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, mako]
