---
- name: Install deps
  ansible.builtin.dnf:
    name: [scdoc]
  tags: [sway, swayidle]

- name: Checkout swayidle
  become: false
  ansible.builtin.git:
    repo: https://github.com/swaywm/swayidle.git
    dest: "{{ sway_sw_dir }}/swayidle"
    version: "{{ sway_swayidle_version }}"
  register: git_clone
  tags: [sway, swayidle]

- name: Meson build
  ansible.builtin.command: meson build -Dsysconfdir=/etc
  changed_when: true
  become: false
  args:
    chdir: "{{ sway_sw_dir }}/swayidle"
  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, swayidle]

- name: Ninja build
  ansible.builtin.command: ninja -C build
  changed_when: true
  become: false
  args:
    chdir: "{{ sway_sw_dir }}/swayidle"
  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, swayidle]

- name: Ninja nstall
  ansible.builtin.command: ninja -C build install
  changed_when: true
  args:
    chdir: "{{ sway_sw_dir }}/swayidle"
  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, swayidle]
