---
- name: Install wlroots dependencies
  ansible.builtin.dnf:
    name: [git, meson, wlc-devel, mesa-libEGL-devel, mesa-libGLES-devel, libdrm-devel, mesa-libgbm-devel, libinput-devel, libxkbcommon-devel, libevdev-devel, pixman-devel, wayland-protocols-devel]
  tags: [sway, wlroots]

- name: Checkout wlroots
  become: false
  ansible.builtin.git:
    repo: https://github.com/swaywm/wlroots.git
    dest: "{{ sway_sw_dir }}/wlroots"
    version: "{{ sway_wlroots_version }}"
  register: git_clone
  tags: [sway, wlroots]

- name: Run command
  ansible.builtin.debug:
    msg: "{{ git_clone }}"
  tags: [sway, wlroots]

- name: Meson build
  ansible.builtin.command: meson build
  changed_when: true
  become: false
  args:
    chdir: "{{ sway_sw_dir }}/wlroots"
  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, wlroots]

- name: Ninja build
  ansible.builtin.command: ninja -C build
  changed_when: true
  become: false
  args:
    chdir: "{{ sway_sw_dir }}/wlroots"
  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, wlroots]

- name: Ninja install
  ansible.builtin.command: ninja -C build install
  changed_when: true
  args:
    chdir: "{{ sway_sw_dir }}/wlroots"
  when: git_clone.remote_url_changed is not defined or git_clone.remote_url_changed
  tags: [sway, wlroots]

- name: Add ldconfig for wlroots
  ansible.builtin.lineinfile:
    path: /etc/ld.so.conf.d/wlroots.conf
    line: /usr/local/lib64
    insertbefore: BOF
    owner: root
    group: root
    mode: "0644"
    create: true
  tags: [sway, wlroots]

- name: Execute ldconfig
  ansible.builtin.command: ldconfig
  changed_when: true
  tags: [sway, wlroots]
