---
- name: Create target directories
  ansible.builtin.file:
    path: "{{ item.target }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  with_items: "{{ acxi_jobs }}"
  when: item.name != "all"
  tags: [acxi, acxi-jobs]

- name: Create acxi_all wrapper
  ansible.builtin.template:
    src: templates/acxi_all.j2
    dest: /usr/local/bin/acxi_all
    owner: root
    group: root
    mode: "0755"
  tags: [acxi, acxi-jobs]

- name: Create all conversion job
  ansible.builtin.cron:
    name: acxi convert all
    job: /usr/local/bin/acxi_all
    minute: "{{ item.minute | default('0') }}"
    hour: "{{ item.hour }}"
    weekday: "{{ item.weekday | default('*') }}"
    state: "{{ item.state | default('present') }}"
    user: "{{ item.user }}"
  with_items: "{{ acxi_jobs }}"
  when: item.name == "all"
  tags: [acxi, acxi-jobs]

- name: Create auto conversion job
  ansible.builtin.cron:
    name: "{{ item.name }}"
    job: /usr/local/bin/acxi --quiet --fork {{ ansible_processor_vcpus }} {% if item.quality is defined %}--quality {{ item.quality }} {% endif %}-o }} -s }} -d {{ item.target }}
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    weekday: "{{ item.weekday | default('*') }}"
    state: "{{ item.state | default('present') }}"
    user: "{{ item.user }}"
  with_items: "{{ acxi_jobs }}"
  when: [item.name != "all", item.hour is defined, item.minute is defined]
  tags: [acxi, acxi-jobs]
