---
- name: Install server that provides VMs
  hosts: vservers
  become: true
  gather_facts: true
  tasks:
    - name: Including role
      ansible.builtin.include_tasks: tasks/hw.yaml
      tags: always

    - name: Including role
      ansible.builtin.include_tasks: tasks/serial.yaml
      tags: always

    - name: Including role
      ansible.builtin.include_tasks: tasks/network.yaml
      tags: always
      when: ansible_os_family | lower == "redhat"

    - name: Including role
      ansible.builtin.include_role:
        name: platform
      tags: always

    - name: Including role
      ansible.builtin.include_role:
        name: libvirt
      tags: always

    - name: Including role
      ansible.builtin.include_role:
        name: smartctl_exporter
      tags: always

    - name: Including role
      ansible.builtin.include_tasks: tasks/packages.yaml
      tags: always

    - name: Including role
      ansible.builtin.include_role:
        name: occult
      vars:
        occult_user: "{{ item.occult_user }}"
        occult_group: "{{ item.occult_group }}"
        occult_config_file: "{{ item.occult_config_file }}"
        occult_autounlock: "{{ item.occult_autounlock }}"
        occult_service_identifier: "{{ item.occult_service_identifier }}"
        occult_config: "{{ item.occult_config }}"
        occult_service_enabled: "{{ item.occult_service_enabled | default(false) }}"
      loop: "{{ occult_configs }}"
      tags: always

    - name: Copy virsh autostart
      ansible.builtin.copy:
        src: files/virsh-autostart
        dest: /usr/local/bin/virsh-autostart
        owner: root
        group: root
        mode: "0755"
      tags: [kubernetes, contrib]

  handlers:
    - name: Regenerate GRUB configuration
      ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
      changed_when: true
      tags: [serial]
