---
- name: Install server that provides VMs
  hosts: vservers
  become: true
  gather_facts: true
  tasks:
    - name: Including role
      ansible.builtin.include_tasks: tasks/hw.yaml
      tags: always

    - name: Including role
      ansible.builtin.include_tasks: tasks/serial.yaml
      tags: always

    - name: Including role
      ansible.builtin.include_tasks: tasks/network.yaml
      tags: always
      when: ansible_os_family | lower == "redhat"

    - name: Including role
      ansible.builtin.include_role:
        name: platform
      tags: always

    - name: Including role
      ansible.builtin.include_role:
        name: libvirt
      tags: always

    - name: Including role
      ansible.builtin.include_role:
        name: smartctl_exporter
      tags: always

    - name: Including role
      ansible.builtin.include_tasks: tasks/packages.yaml
      tags: always

    - name: Including role
      ansible.builtin.include_role:
        name: occult
      tags: always

    - name: Copy virsh autostart
      ansible.builtin.copy:
        src: files/virsh-autostart
        dest: "{{ virsh_autostart_file }}"
        owner: root
        group: root
        mode: "0755"
      tags: [virsh, autostart]

  handlers:
    - name: Regenerate GRUB configuration
      ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
      changed_when: true
      tags: [serial]
