---
go_arch_map:  # noqa: var-naming[no-role-prefix]
  i386: "386"
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
  armv6l: arm6vl

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"  # noqa: var-naming[no-role-prefix]
go_os: "{{ ansible_system | lower }}"  # noqa: var-naming[no-role-prefix]
