---
- name: Install spotifyd
  ansible.builtin.package:
    name: [mpd]
  tags: [mpd, mpd-install]

- name: Create user {{ spotifyd_user }}
  ansible.builtin.user:
    name: "{{ spotifyd_user }}"
    groups: audio
    append: true
  tags: [spotifyd, spotifyd-install]
