---
- name: "Set variables"
  ansible.builtin.set_fact:
    directory_exporter_local_binary: ""
    directory_exporter_installed_version: ""
    directory_exporter_desired_version: "{{ directory_exporter_version | default('') }}"
    directory_exporter_download_archive: ""
    directory_exporter_download_signature: ""
    directory_exporter_stopped_service: ""
    directory_exporter_github_release: ""
    directory_exporter_go_os: ""
    directory_exporter_go_arch: ""
    directory_exporter_checksum_signature_file: ""
    directory_exporter_checksum_file: ""
    directory_exporter_full_filename: ""
    directory_exporter_release_checksum: ""
  tags: [directory-exporter, directory-exporter-install, deps]

- name: Check for existing binary
  ansible.builtin.stat:
    path: /usr/local/bin/{{ binary_name }}
  register: directory_exporter_local_binary
  tags: [directory-exporter, directory-exporter-install, deps]

- name: Check installed version
  when: directory_exporter_local_binary.stat.exists
  tags: [directory-exporter, directory-exporter-install, deps]
  block:
    - name: Check installed version
      ansible.builtin.shell: set -o pipefail &&  /usr/local/bin/{{ binary_name }} -version 2>&1 | awk '{print $1}'
      register: directory_exporter_installed_version
      changed_when: false

    - name: Register local version
      ansible.builtin.set_fact:
        directory_exporter_installed_version: "{{ directory_exporter_installed_version.stdout }}"
      changed_when: false

    - name: Print debug information
      ansible.builtin.debug:
        msg: "Installed version: {{ directory_exporter_installed_version }}"
      changed_when: false

- name: Fetch latest release information from github
  when: directory_exporter_desired_version is not defined or not directory_exporter_desired_version
  tags: [directory-exporter, directory-exporter-install, deps]
  block:
    - name: Print debug information
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ github_repo }}/releases/latest
        return_content: true
      register: directory_exporter_github_release
      retries: 3
      delay: 5
      until: directory_exporter_github_release is not failed

    - name: Set github release
      ansible.builtin.set_fact:
        directory_exporter_desired_version: "{{ directory_exporter_github_release.json.tag_name }}"
      changed_when: false

    - name: Print latest GitHub version
      ansible.builtin.debug:
        msg: "Latest GitHub version: {{ directory_exporter_desired_version }}"
      changed_when: false

- name: "Download artifacts"
  when: not directory_exporter_local_binary.stat.exists or directory_exporter_desired_version != directory_exporter_installed_version
  tags: [directory-exporter, directory-exporter-install, deps]
  block:
    - name: Generate temp dir
      become: false
      ansible.builtin.tempfile:
        state: directory
        suffix: "{{ binary_name }}"
      register: directory_exporter_download_dir

    - name: Set vars for generating download link
      ansible.builtin.set_fact:
        directory_exporter_go_os: "{{ ansible_system | lower }}"
        directory_exporter_go_arch: "{{ 'x86_64' if ansible_architecture == 'x86_64' else 'armv6' if ansible_architecture == 'armv6l' else 'armv7' if ansible_architecture == 'armv7l' else 'arm64' if ansible_architecture == 'aarch64' }}"
      changed_when: false

    - name: Set filenames
      ansible.builtin.set_fact:
        directory_exporter_checksum_signature_file: "{{ directory_exporter_download_dir }}/{{ binary_name }}-checksums.sha256.sig"
        directory_exporter_checksum_file: "{{ directory_exporter_download_dir }}/{{ binary_name }}-checksums.sha256"
        directory_exporter_full_filename: "{{ binary_name }}-{{ directory_exporter_go_os }}-{{ directory_exporter_go_arch }}"
      changed_when: false

    - name: Get checksum for archive
      ansible.builtin.set_fact:
        directory_exporter_release_checksum: "{{ item.split(' ')[0] }}"
      when: [directory_exporter_full_filename in item, (not directory_exporter_local_binary.stat.exists or directory_exporter_installed_version != directory_exporter_desired_version)]
      with_items: ["{{ lookup('url', 'https://github.com/{{ github_repo }}/releases/download/' + directory_exporter_desired_version + '/checksum.sha256', wantlist=True) | list }}"]

    - name: Download binary
      become: false
      ansible.builtin.get_url:
        url: https://github.com/{{ github_repo }}/releases/download/{{ directory_exporter_desired_version }}/{{ directory_exporter_full_filename }}
        dest: "{{ directory_exporter_download_dir }}/{{ directory_exporter_full_filename }}"
        checksum: sha256:{{ directory_exporter_release_checksum }}
        mode: "0640"
      register: directory_exporter_download_archive
      until: directory_exporter_download_archive is succeeded
      retries: 5
      delay: 2

    - name: Download release checksum
      become: false
      ansible.builtin.get_url:
        url: https://github.com/{{ github_repo }}/releases/download/{{ directory_exporter_desired_version }}/checksum.sha256
        dest: "{{ directory_exporter_checksum_file }}"
        mode: "0640"
      register: directory_exporter_download_signature
      until: directory_exporter_download_signature is succeeded
      retries: 5
      delay: 2

    - name: Download release checksum signature
      become: false
      ansible.builtin.get_url:
        url: https://github.com/{{ github_repo }}/releases/download/{{ directory_exporter_desired_version }}/checksum.sha256.sig
        dest: "{{ directory_exporter_checksum_signature_file }}"
        mode: "0640"
      register: directory_exporter_download_signature
      until: directory_exporter_download_signature is succeeded
      retries: 5
      delay: 2

    - name: Verify signature
      ansible.builtin.command: signify -V -p /etc/signify/soerenschneider-github.pub -m {{ directory_exporter_checksum_file }}
      changed_when: false

    - name: Stop service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: stopped
      failed_when: false
      register: directory_exporter_stopped_service

    - name: Copy binaries
      ansible.builtin.copy:
        src: "{{ directory_exporter_download_dir }}/{{ directory_exporter_full_filename }}"
        dest: /usr/local/bin/{{ item }}
        remote_src: true
        mode: "0755"
        owner: root
        group: root
      with_items: ["{{ binary_name }}"]

  always:
    - name: Delete downloaded files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      with_items: ["{{ directory_exporter_download_dir }}"]
      failed_when: false

    - name: Restart service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: restarted
      when: directory_exporter_stopped_service is defined and directory_exporter_stopped_service is changed
