---
- name: Add group
  ansible.builtin.group:
    name: "{{ directory_exporter_group }}"
    system: true
  tags: [directory-exporter, directory-exporter-install]

- name: Add user
  ansible.builtin.user:
    name: "{{ directory_exporter_user }}"
    shell: /bin/false
    system: true
    groups: "{{ directory_exporter_group }}"
  tags: [directory-exporter, directory-exporter-install]

- name: Including tasks
  ansible.builtin.include_tasks: install-github.yml
  vars:
    binary_name: directory-exporter
    github_repo: soerenschneider/directory-exporter
    service_name: directory-exporter
  tags: [directory-exporter, directory-exporter-install, deps]

- name: Add config
  ansible.builtin.copy:
    content: "{{ directory_exporter_config | to_nice_json }}"
    dest: "{{ directory_exporter_config_file }}"
    owner: "{{ directory_exporter_user }}"
    group: "{{ directory_exporter_group }}"
    mode: "0644"
  notify: Restart directory-exporter
  tags: [directory-exporter, directory-exporter-configure]

- name: Add systemd service
  ansible.builtin.template:
    src: directory-exporter.service.j2
    dest: /etc/systemd/system/directory-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart directory-exporter
  tags: [directory-exporter, directory-exporter-configure]

- name: Enable/disable directory-exporter
  ansible.builtin.service:
    name: "{{ directory_exporter_service_name }}"
    enabled: true
  tags: [directory-exporter, directory-exporter-configure]
