---
- name: Setup routers
  hosts: routers
  become: true
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
  vars:
    nftables_variables_file: /etc/nftables/nftables-variables.nft

  tasks:
    - name: "Run tasks network.yaml"
      ansible.builtin.include_tasks: tasks/network.yaml
      tags: always

    - name: "Run role platform"
      ansible.builtin.include_role:
        name: platform
      tags: always

    - name: "Run role unbound"
      ansible.builtin.include_role:
        name: unbound
      tags: always

    - name: "Run role alertmanager"
      ansible.builtin.include_role:
        name: alertmanager
      tags: always

    - name: "Run role device_stalker"
      ansible.builtin.include_role:
        name: device_stalker
      tags: always

    - name: "Run role ssh_aegis"
      ansible.builtin.include_role:
        name: ssh_aegis
      tags: always

    - name: "Run tasks haproxy.yaml"
      ansible.builtin.include_tasks: tasks/haproxy.yaml
      tags: always

    - name: "Run role wireguard"
      ansible.builtin.include_role:
        name: wireguard
      tags: always

    - name: "Run tasks firewall.yaml"
      ansible.builtin.include_tasks: tasks/firewall.yaml
      tags: always

    - name: "Run tasks sysctl.yaml"
      ansible.builtin.include_tasks: tasks/sysctl.yaml
      tags: always

    - name: "Run tasks dhcpd.yml"
      ansible.builtin.include_tasks: tasks/dhcpd.yml
      tags: always

    - name: "Run tasks ntpd.yml"
      ansible.builtin.include_tasks: tasks/ntpd.yml
      tags: always

    - name: "Run role dyndns"
      ansible.builtin.include_role:
        name: dyndns
      tags: always
