---
- name: Set sysctl value
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "2099999999"
    state: present
  tags: [sysctl, limits, k0s, k8s]

- name: Set sysctl value
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: "2099999999"
    state: present
  tags: [sysctl, limits, k0s, k8s]

- name: Set sysctl value
  ansible.posix.sysctl:
    name: fs.inotify.max_queued_events
    value: "2099999999"
    state: present
  tags: [sysctl, limits, k0s, k8s]
