---
- name: Make sure .config exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
    state: "directory"
  tags:
    - dirs

- name: Create sw dir
  ansible.builtin.file:
    path: "{{ sw_dir }}"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
    state: "directory"
  tags: dirs

- name: Create contacts
  ansible.builtin.file:
    path: "{{ user_home }}/.contacts"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    state: "directory"
    mode: "0700"
  tags: dav

- name: Create calendars
  ansible.builtin.file:
    path: "{{ user_home }}/.calendars"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    state: "directory"
    mode: "0700"
  tags: dav
