---
- name: "Load package list"
  ansible.builtin.include_vars:
    file: "{{ 'settings/packages-macos-darwin.yaml' if ansible_facts['os_family'] == 'Darwin' else 'settings/packages-linux-' + ansible_facts['distribution'] | lower + '.yaml' }}"

  tags: packages

- name: "Install homebrew packages (Mac)"
  when: ansible_facts['system'] == "Darwin"
  block:
    - name: "Install packages (Mac)"
      ansible.builtin.package:
        name: "{{ install_packages }}"
      tags: packages

    - name: "Uninstall packages"
      ansible.builtin.package:
        name: "{{ uninstall_packages | default([]) }}"
        state: absent
      tags: packages

- name: "Include task rpmfusion"
  ansible.builtin.include_tasks: tasks/rhel-rpmfusion.yml
  when:
    - ansible_facts['system'] == "Linux"
    - ansible_facts["os_family"] == "RedHat"
  tags: always

- name: "Install distribution packages (Linux)"
  when: ansible_facts['system'] == "Linux"
  block:
    - name: "Install packages (Linux)"
      become: true
      when: ansible_facts['system'] == "Linux"
      ansible.builtin.package:
        name: "{{ install_packages }}"
      tags: packages

    - name: "Uninstall packages"
      become: true
      ansible.builtin.package:
        name: "{{ uninstall_packages | default([]) }}"
        state: absent
      tags: packages

- name: "Install Flatpak packages (Linux)"
  when: ansible_facts['system'] == "Linux"
  block:
    - name: "Add the flathub flatpak repository remote"
      community.general.flatpak_remote:
        name: "flathub"
        state: "present"
        flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
      tags: [packages, flatpak]

    - name: "Install flatpak packages"
      community.general.flatpak:
        name: "{{ install_flatpaks }}"
      tags: [packages, flatpak]
