---
- name: Import ssh public keys
  ansible.builtin.known_hosts:
    key: "{{ item.key }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    path: "/etc/ssh/ssh_known_hosts"
  with_items: "{{ ssh_known_hosts | selectattr('name', 'in', ['github.com', 'gitlab.com']) | list }}"
  become: true
  tags: repos

- name: Make sure git directories exists
  become: false
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
  with_items:
    - "{{ github_dir }}"
  tags: repos

- name: "Include task repos_checkout"
  ansible.builtin.include_tasks: repos-checkout.yml
  with_items: "{{ repos }}"
  tags: repos

- name: "Install dotfiles"
  ansible.builtin.command: "bash ./install.sh"
  become: false
  args:
    chdir: "{{ github_dir }}/dotfiles"
  register: output
  changed_when: true
  tags: repos

- name: "Install scripts"
  ansible.builtin.command: make install
  become: false
  changed_when: true
  args:
    chdir: "{{ github_dir }}/scripts"
  tags: repos

- name: "Create pass link to repo"
  become: false
  ansible.builtin.file:
    src: "{{ github_dir }}/abrakadabra"
    dest: "{{ user_home }}/.password-store"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    state: link
  tags: repos
