---
- name: "Load sc config..."
  ansible.builtin.include_vars:
    file: "{{ inventory_path }}/group_vars/desktop/sc.yaml"
  ignore_errors: false
  tags: sc

- name: Create sc profiles file
  ansible.builtin.copy:
    dest: "{{ user_home_dir.stat.path }}/.sc-profiles.yaml"
    content: "{{ sc_profiles }}"
    owner: "soeren"
    group: "soeren"
    mode: "0640"
  become: true
  become_user: soeren
  when: sc_profiles is defined
  tags: [sc]