---
- name: "Load sc config..."
  ansible.builtin.include_vars:
    file: "{{ inventory_path }}/group_vars/desktop/sc.yaml"
  ignore_errors: false
  tags: sc

- name: "Create sc profiles file"
  ansible.builtin.copy:
    dest: "{{ user_home }}/.sc-profiles.yaml"
    content: "{{ sc_profiles }}"
    owner: "ansible_facts['user_id']"
    group: "ansible_facts['user_id']"
    mode: "0600"
  when: sc_profiles is defined
  tags: [sc]
