---
- name: Create signify dir
  ansible.builtin.file:
    path: /etc/signify
    state: directory
    owner: root
    group: "{% if ansible_system == 'OpenBSD' %}wheel{% else %}root{% endif %}"
    mode: "0755"
  tags: [signify, base, base-signify]

- name: Add signify keys
  ansible.builtin.copy:
    dest: /etc/signify/{{ item.filename }}
    content: "{{ item.public_key }}"
    owner: root
    group: "{% if ansible_system == 'OpenBSD' %}wheel{% else %}root{% endif %}"
    mode: "0644"
  with_items: "{{ signify_keys }}"
  tags: [signify, base, base-signify]
