---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
  tags:
    - zsh
    - ohmyzsh

- name: Set zsh as default shell (Linux)
  when: ansible_facts['system'] == "Linux"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /usr/bin/zsh
  tags:
    - zsh
    - ohmyzsh

- name: Set zsh as default shell (Darwin)
  when: ansible_facts['system'] == "Darwin"
  become: true
  ansible.builtin.command: "chsh -s /opt/homebrew/bin/zsh {{ ansible_facts['user_id'] }}"
  tags:
    - zsh
    - ohmyzsh

- name: Checkout oh-my-zsh
  become: false
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ user_home }}/.oh-my-zsh"
  # noqa: latest[git]
  tags:
    - ohmyzsh
    - zsh

- name: Create completions dir
  become: false
  ansible.builtin.file:
    path: "{{ user_home }}/.oh-my-zsh/completions"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
    state: directory
  tags:
    - ohmyzsh
    - zsh
